### PR TITLE
Fix clang libcxx warnings <2.0.x> [8905]

### LINKED ISSUE #1297: several compiler warnings with clang+libcxx [8887]
See:
* https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/482/gcc/folder.1539294886/

  * `TypeObjectFactory.cpp:2076`:

    > loop variable 'a_param' of type 'const eprosima::fastrtps::types::AppliedAnnotationParameter' creates a copy from type 'const eprosima::fastrtps::types::AppliedAnnotationParameter' [-Wrange-loop-construct] for (const AppliedAnnotationParameter a_param : anno_params)

  * `TypeObjectFactory.cpp:2101`:

    > loop variable 'a_param' of type 'const eprosima::fastrtps::types::AppliedAnnotationParameter' creates a copy from type 'const eprosima::fastrtps::types::AppliedAnnotationParameter' [-Wrange-loop-construct] for (const AppliedAnnotationParameter a_param : anno_params)

* https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/482/gcc/folder.1941504058/

  * `sqlite3.c:107898`:

    > implicit conversion from 'long long' to 'double' changes value from 9223372036854775806 to 9223372036854775808 [-Wimplicit-int-float-conversion] if( n==0 && r>=0 && r

  * `sqlite3.c:107900`:

    > implicit conversion from 'long long' to 'double' changes value from 9223372036854775806 to 9223372036854775808 [-Wimplicit-int-float-conversion] }else if( n==0 && r<0 && (-r)

* https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/482/gcc/folder.236002918/

  * `SharedMemUUID.hpp:132`:

    > definition of implicit copy constructor for 'UUID<8>' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy] UUID& operator =(

* https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/482/gcc/folder.360225354/

  * `tree_iterator.hpp:73`:

    > definition of implicit copy assignment operator for 'tree_iterator, 0>::block_ctrl, boost::intrusive::rbtree_node_traits, true>, boost::intrusive::normal_link, boost::intrusive::dft_tag, 3>, false>' is deprecated because it has a user-declared copy constructor [-Wdeprecated-copy] BOOST_INTRUSIVE_FORCEINLINE tree_iterator(tree_iterator const& other)

    > definition of implicit copy assignment operator for 'tree_iterator, true>, boost::intrusive::dft_tag, boost::intrusive::safe_link, boost::intrusive::RbTreeBaseHookId>, char, unsigned int>, boost::intrusive::rbtree_node_traits, true>, boost::intrusive::safe_link, boost::intrusive::dft_tag, 3>, false>' is deprecated because it has a user-declared copy constructor [-Wdeprecated-copy] BOOST_INTRUSIVE_FORCEINLINE tree_iterator(tree_iterator const& other)

* https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/482/gcc/folder.-365770583/

  * `sp_counted_base_clang.hpp:27`:

    > '_Atomic' is a C11 extension [-Wc11-extensions] typedef _Atomic( boost::int_least32_t ) atomic_int_least32_t;

### PR DESCRIPTION
**Pull request by MiguelCompany**
Fix #1297 by:

* Adding ref to ranged loops on TypeObjectFactory
* Removing assign operator on SharedMemUUID, as default one would do the same.
* Upgrading sqlite to 3.32.3
* Upgrading boost files to 1.73.0
* Applying boostorg/smart_ptr@066b398114ab48c81c875e95459c15c2416a7891

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2363/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2163/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2354/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2376/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2176/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2367/)

File: thirdparty/boost/include/boost/smart_ptr/detail/sp_counted_base_clang.hpp [hunk 1]
```diff
@@ -26,6 +26,16 @@ namespace boost
...
+#if defined(__clang__)
+# pragma clang diagnostic push
+#endif
+
+#if defined(__clang__) && defined(__has_warning)
+# if __has_warning( "-Wc11-extensions" )
+#  pragma clang diagnostic ignored "-Wc11-extensions"
+# endif
+#endif
+
```
Comment (LuisGP) [inline thirdparty/boost/include/boost/smart_ptr/detail/sp_counted_base_clang.hpp:38]: I'm not comfortable modifying a third-party code...

Comment (MiguelCompany) [reply thirdparty/boost/include/boost/smart_ptr/detail/sp_counted_base_clang.hpp:38]: It is applying boostorg/smart_ptr@066b398 from upstream
