### PR TITLE
[15015] Improve read/take performance

### LINKED ISSUE #2779: [15016] CPU usage increase in v2.6.0 comparing with v2.2.0
### Expected behavior

Almost the same CPU usage

### Current behavior

v2.6.0 have more CPU usage than v2.2.0

### Steps to reproduce

Hardware platform is i.MX 6.   
Test program is the same and the used version of fastdds is v2.6.0 and v2.2.0   

One subscriber is on this hardware device.  There are other 5 devices which will be started and send message to this device.   
At subscriber side,  there are about 500 messages received immediately after matching.   
During this period,  
v2.2.0:   CPU usage (30% ~ 70%) will last for about 1 minute.  
v2.6.0:   CPU usage (28% ~ 72%) will last for about 3 minutes. 

While receiving messages from one device,   
v2.2.0: CPU usage is about 2.5%.  
v2.6.0: CPU usage is about 7.5%.  

I am modifying DDS sample code to reproduce it. After done, I will attach code.  

### Fast DDS version/commit

v2.2.0 and v2.6.0

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

For v2.6.1  
If receive 100 messages, CPU usage is about 20%.  
If receive 500 messages, CPU usage is about 50%.
If receive 1000 messages, CPU usage is about 100%.

After analysis, the function using much CPU is

https://github.com/eProsima/Fast-DDS/blob/master/src/cpp/fastdds/subscriber/DataReaderImpl.cpp#L659  

And

https://github.com/eProsima/Fast-DDS/blob/master/src/cpp/fastdds/subscriber/DataReaderImpl.cpp#L673 (It also calls above `lookup_instance`).   

Above information isn't enough. I will continue to supplement information.

### PR DESCRIPTION
**Pull request by MiguelCompany**
## Description

This PR highly improves the performance of read / take methods when the number of instances on a keyed topic is high.

The main ideas behind it are:
* Using iterators on ReadTakeCommand
* Using a specific collection for instances with available data on DataReaderHistory

This should fix #2779.

@mergifyio backport 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
    - [x] DataReaderTests
    - [x] BlackboxTests_DDS_PIM.PubSubBasic
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by MiguelCompany** [comment]
@richiprosima Please test mac

**Review by fujitatomoya — COMMENTED** [review]
@MiguelCompany we will evaluate this fix with our application, i will get back to you once we have confirmation.

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by fujitatomoya** [comment]
@MiguelCompany confirmed that this PR fixes our issue.

**Review by JLBuenoLopez-eProsima — COMMENTED** [review]
Only some nitpicks. Changes LGTM!

File: src/cpp/fastdds/subscriber/history/DataReaderHistory.hpp [hunk 1]
```diff
@@ -195,42 +222,72 @@ class DataReaderHistory : public eprosima::fastrtps::rtps::ReaderHistory
...
      *          `handle = HANDLE_NIL` and `exact = false`.
      */
-    std::pair<bool, instance_info> lookup_instance(
+    std::pair<bool, instance_info> lookup_available_instance(
             const InstanceHandle_t& handle,
-            bool exact) const;
+            bool exact);
+
+    /**
+     * @brief Advance an iterator to an instance with available data to the next instance.
```
Comment (JLBuenoLopez-eProsima) [inline src/cpp/fastdds/subscriber/history/DataReaderHistory.hpp:278]:
```suggestion
     * @brief Given an instance advance the iterator to the next instance with available data.
```

**Review by JLBuenoLopez-eProsima — COMMENTED** [review]
Nitpick

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM with green CI

**Comment by MiguelCompany** [comment]
@mergifyio backport 2.6.x
