### PR TITLE
[20584] Effectively assert automatic/manual_by_participant liveliness

### LINKED ISSUE #4373: The Reader's Liveliness state does not change when the connection with the remote Participant is lost
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

`on_liveliness_changed()` should be called  when `lease_duration` expires.

### Current behavior

If the communication with the Participant is interrupted, the `on_liveliness_changed()` is called after 20 seconds instead of the 1.6 seconds specified in the `lease_duration` parameter

### Steps to reproduce

Developed a test based on the HelloWorld example code in accordance with the attached patch. On the Subscriber's side, another Topic Reader is added with the name `HelloWorldTopic_2` (created by the argument -a). In addition to the `HelloWorldTopic` Topic, a Writer can also send the `HelloWorldTopic_2` topic (when using the -a argument).
To run the test, you need to open three terminals and run the following commands:
`./DDSHelloWorldExample subscriber -a`
`./DDSHelloWorldExample publisher -s 0 -i 2000`
`./DDSHelloWorldExample publisher -s 0 -i 2000 -a`

After about 10 seconds after launch, press `Ctrl-C` in the second terminal, which will end the application with one Topic Writer with name `HelloWorldTopic`. As a result, only one Topic with the name `HelloWorldTopic_2` should be received (corresponds to the timestamp 265.837 on the log shown below).
After 1.6 seconds after the termination of the first application with the Topic `HelloWorldTopic` Writer, the `on_liveliness_changed()` event is expected to occur on the receiving side because the connection with the Participant was lost. But this does not happen at the expected moment in time. The specified event occurs much later - see timestamp 286.365.
The difference between the actual and expected moment of occurrence of the event `on_liveliness_changed()` is 20 seconds, which corresponds to the leaseDuration parameter from DiscoverySettings. Thus, the initiator of the event was the fact that a timeout occurred in PDP, and not in Liveliness subsystem, which is incorrect in this case.
At the time of the corresponding timestamp 296.540, the application with the Topic `HelloWorldTopic_2` Writer in the third terminal is terminated by pressing `Ctrl-C`. And in the log we see the correct sequence of events `on_liveliness_changed()`: a liveliness event occurs at 296.540 with `alive_count=0 not_alive_count=1 alive_count_change=-1 not_alive_count_change=1` and then at 314.941 with `alive_count=0 not_alive_count=0 alive_count_change=0 not_alive_count_change=-1`.

Terminal number 1 (with two Readers as part of one Participant) will take the following form:
```
Starting 
Subscriber running. Please press enter to stop the Subscriber
252.863 s: Subscriber HelloWorldTopic matched.
253.763 s: on_liveliness_changed() called for Reader HelloWorldTopic alive_count=1 not_alive_count=0 alive_count_change=1 not_alive_count_change=0 last_publication_handle=1.f.f7.f3.2a.12.5d.e1.0.0.0.0.0.0.1.3
254.863 s: HelloWorldTopic receive message: HelloWorld 2 RECEIVED
256.864 s: HelloWorldTopic receive message: HelloWorld 3 RECEIVED
258.865 s: HelloWorldTopic receive message: HelloWorld 4 RECEIVED
259.835 s: Subscriber HelloWorldTopic_2 matched.
260.064 s: on_liveliness_changed() called for Reader HelloWorldTopic_2 alive_count=1 not_alive_count=0 alive_count_change=1 not_alive_count_change=0 last_publication_handle=1.f.f7.f3.33.12.89.8.0.0.0.0.0.0.1.3
260.865 s: HelloWorldTopic receive message: HelloWorld 5 RECEIVED
261.836 s: HelloWorldTopic_2 receive message: HelloWorld 2 RECEIVED
262.866 s: HelloWorldTopic receive message: HelloWorld 6 RECEIVED
263.836 s: HelloWorldTopic_2 receive message: HelloWorld 3 RECEIVED
264.867 s: HelloWorldTopic receive message: HelloWorld 7 RECEIVED
265.837 s: HelloWorldTopic_2 receive message: HelloWorld 4 RECEIVED
267.838 s: HelloWorldTopic_2 receive message: HelloWorld 5 RECEIVED
269.838 s: HelloWorldTopic_2 receive message: HelloWorld 6 RECEIVED
271.839 s: HelloWorldTopic_2 receive message: HelloWorld 7 RECEIVED
273.839 s: HelloWorldTopic_2 receive message: HelloWorld 8 RECEIVED
275.840 s: HelloWorldTopic_2 receive message: HelloWorld 9 RECEIVED
277.841 s: HelloWorldTopic_2 receive message: HelloWorld 10 RECEIVED
279.841 s: HelloWorldTopic_2 receive message: HelloWorld 11 RECEIVED
281.842 s: HelloWorldTopic_2 receive message: HelloWorld 12 RECEIVED
283.843 s: HelloWorldTopic_2 receive message: HelloWorld 13 RECEIVED
285.843 s: HelloWorldTopic_2 receive message: HelloWorld 14 RECEIVED
286.365 s: on_liveliness_changed() called for Reader HelloWorldTopic alive_count=0 not_alive_count=0 alive_count_change=-1 not_alive_count_change=0 last_publication_handle=1.f.f7.f3.2a.12.5d.e1.0.0.0.0.0.0.1.3
286.366 s: Subscriber HelloWorldTopic unmatched.
287.844 s: HelloWorldTopic_2 receive message: HelloWorld 15 RECEIVED
289.845 s: HelloWorldTopic_2 receive message: HelloWorld 16 RECEIVED
291.845 s: HelloWorldTopic_2 receive message: HelloWorld 17 RECEIVED
293.846 s: HelloWorldTopic_2 receive message: HelloWorld 18 RECEIVED
296.540 s: on_liveliness_changed() called for Reader HelloWorldTopic_2 alive_count=0 not_alive_count=1 alive_count_change=-1 not_alive_count_change=1 last_publication_handle=1.f.f7.f3.33.12.89.8.0.0.0.0.0.0.1.3
314.941 s: on_liveliness_changed() called for Reader HelloWorldTopic_2 alive_count=0 not_alive_count=0 alive_count_change=0 not_alive_count_change=-1 last_publication_handle=1.f.f7.f3.33.12.89.8.0.0.0.0.0.0.1.3
314.941 s: Subscriber HelloWorldTopic_2 unmatched.
```
**HelloWorld example code patch:**
```
diff --git a/examples/cpp/dds/HelloWorldExample/HelloWorldPublisher.cpp b/examples/cpp/dds/HelloWorldExample/HelloWorldPublisher.cpp
index 86f3e0009..8e3e55cad 100644
--- a/examples/cpp/dds/HelloWorldExample/HelloWorldPublisher.cpp
+++ b/examples/cpp/dds/HelloWorldExample/HelloWorldPublisher.cpp
@@ -40,7 +40,8 @@ HelloWorldPublisher::HelloWorldPublisher()
 }
 
 bool HelloWorldPublisher::init(
-        bool use_env)
+        bool use_env,
+        bool use_alternative_topic)
 {
     hello_.index(0);
     hello_.message("HelloWorld");
@@ -90,7 +91,7 @@ bool HelloWorldPublisher::init(
     }
 
     topic_ = participant_->create_topic(
-        "HelloWorldTopic",
+        use_alternative_topic? "HelloWorldTopic_2" : "HelloWorldTopic",
         "HelloWorld",
         tqos);
 
@@ -107,6 +108,10 @@ bool HelloWorldPublisher::init(
         publisher_->get_default_datawriter_qos(wqos);
     }
 
+    wqos.liveliness().kind = AUTOMATIC_LIVELINESS_QOS;
+    wqos.liveliness().lease_duration = eprosima::fastrtps::Time_t(1, 000000000);
+    wqos.liveliness().announcement_period = eprosima::fastrtps::Time_t(0, 900000000);
+
     writer_ = publisher_->create_datawriter(
         topic_,
         wqos,
diff --git a/examples/cpp/dds/HelloWorldExample/HelloWorldPublisher.h b/examples/cpp/dds/HelloWorldExample/HelloWorldPublisher.h
index b764dfc67..b260b962d 100644
--- a/examples/cpp/dds/HelloWorldExample/HelloWorldPublisher.h
+++ b/examples/cpp/dds/HelloWorldExample/HelloWorldPublisher.h
@@ -36,7 +36,8 @@ public:
 
     //!Initialize
     bool init(
-            bool use_env);
+            bool use_env,
+            bool use_alternative_topic);
 
     //!Publish a sample
     bool publish(
diff --git a/examples/cpp/dds/HelloWorldExample/HelloWorldSubscriber.cpp b/examples/cpp/dds/HelloWorldExample/HelloWorldSubscriber.cpp
index 6823a32f4..8b3b5e48b 100644
--- a/examples/cpp/dds/HelloWorldExample/HelloWorldSubscriber.cpp
+++ b/examples/cpp/dds/HelloWorldExample/HelloWorldSubscriber.cpp
@@ -32,17 +32,31 @@
 
 using namespace eprosima::fastdds::dds;
 
+std::string get_time()
+{
+    using namespace std::chrono;
+
+    auto t = (duration_cast<duration<double>>(steady_clock::now().time_since_epoch())).count();
+    
+    char buf[256];
+    std::snprintf(buf, sizeof(buf), "%.3f s: ", t);
+    return buf;
+}
+
 HelloWorldSubscriber::HelloWorldSubscriber()
     : participant_(nullptr)
     , subscriber_(nullptr)
     , topic_(nullptr)
+    , topic_2_(nullptr)
     , reader_(nullptr)
+    , reader_2_(nullptr)
     , type_(new HelloWorldPubSubType())
 {
 }
 
 bool HelloWorldSubscriber::init(
-        bool use_env)
+        bool use_env,
+        bool use_additional_reader)
 {
     DomainParticipantQos pqos = PARTICIPANT_QOS_DEFAULT;
     pqos.name("Participant_sub");
@@ -106,6 +120,7 @@ bool HelloWorldSubscriber::init(
         subscriber_->get_default_datareader_qos(rqos);
     }
 
+    rqos.liveliness().lease_duration = eprosima::fastrtps::Time_t(1, 600000000);
     reader_ = subscriber_->create_datareader(topic_, rqos, &listener_);
 
     if (reader_ == nullptr)
@@ -113,6 +128,26 @@ bool HelloWorldSubscriber::init(
         return false;
     }
 
+    if (use_additional_reader)
+    {
+        topic_2_ = participant_->create_topic(
+            "HelloWorldTopic_2",
+            "HelloWorld",
+            tqos);
+ 
+        if (topic_2_ == nullptr)
+        {
+            return false;
+        }
+
+        reader_2_ = subscriber_->create_datareader(topic_2_, rqos, &listener_);
+
+        if (reader_2_ == nullptr)
+        {
+            return false;
+        }
+    }
+
     return true;
 }
 
@@ -122,10 +157,18 @@ HelloWorldSubscriber::~HelloWorldSubscriber()
     {
         subscriber_->delete_datareader(reader_);
     }
+    if (reader_2_ != nullptr)
+    {
+        subscriber_->delete_datareader(reader_2_);
+    }
     if (topic_ != nullptr)
     {
         participant_->delete_topic(topic_);
     }
+    if (topic_2_ != nullptr)
+    {
+        participant_->delete_topic(topic_2_);
+    }
     if (subscriber_ != nullptr)
     {
         participant_->delete_subscriber(subscriber_);
@@ -134,18 +177,18 @@ HelloWorldSubscriber::~HelloWorldSubscriber()
 }
 
 void HelloWorldSubscriber::SubListener::on_subscription_matched(
-        DataReader*,
+        DataReader* reader,
         const SubscriptionMatchedStatus& info)
 {
     if (info.current_count_change == 1)
     {
         matched_ = info.total_count;
-        std::cout << "Subscriber matched." << std::endl;
+        std::cout << get_time() << "Subscriber " << reader->get_topicdescription()->get_name() << " matched." << std::endl;
     }
     else if (info.current_count_change == -1)
     {
         matched_ = info.total_count;
-        std::cout << "Subscriber unmatched." << std::endl;
+        std::cout << get_time() << "Subscriber " << reader->get_topicdescription()->get_name() << " unmatched." << std::endl;
     }
     else
     {
@@ -164,11 +207,24 @@ void HelloWorldSubscriber::SubListener::on_data_available(
         {
             samples_++;
             // Print your structure data here.
-            std::cout << "Message " << hello_.message() << " " << hello_.index() << " RECEIVED" << std::endl;
+            std::cout << get_time() << reader->get_topicdescription()->get_name() << " receive message: " << hello_.message() << " " << hello_.index() << " RECEIVED" << std::endl;
         }
     }
 }
 
+void HelloWorldSubscriber::SubListener::on_liveliness_changed(
+        eprosima::fastdds::dds::DataReader* reader,
+        const eprosima::fastdds::dds::LivelinessChangedStatus& status)
+{
+    std::cout << get_time() << "on_liveliness_changed() called" << 
+        " for Reader " << reader->get_topicdescription()->get_name() <<
+        " alive_count=" << status.alive_count <<
+        " not_alive_count=" << status.not_alive_count << 
+        " alive_count_change=" << status.alive_count_change << 
+        " not_alive_count_change=" << status.not_alive_count_change << 
+        " last_publication_handle=" << status.last_publication_handle << "\n";
+}
+
 void HelloWorldSubscriber::run()
 {
     std::cout << "Subscriber running. Please press enter to stop the Subscriber" << std::endl;
diff --git a/examples/cpp/dds/HelloWorldExample/HelloWorldSubscriber.h b/examples/cpp/dds/HelloWorldExample/HelloWorldSubscriber.h
index ecd897bd5..585f9446f 100644
--- a/examples/cpp/dds/HelloWorldExample/HelloWorldSubscriber.h
+++ b/examples/cpp/dds/HelloWorldExample/HelloWorldSubscriber.h
@@ -37,7 +37,8 @@ public:
 
     //!Initialize the subscriber
     bool init(
-            bool use_env);
+            bool use_env,
+            bool use_additional_reader);
 
     //!RUN the subscriber
     void run();
@@ -53,8 +54,10 @@ private:
     eprosima::fastdds::dds::Subscriber* subscriber_;
 
     eprosima::fastdds::dds::Topic* topic_;
+    eprosima::fastdds::dds::Topic* topic_2_;
 
     eprosima::fastdds::dds::DataReader* reader_;
+    eprosima::fastdds::dds::DataReader* reader_2_;
 
     eprosima::fastdds::dds::TypeSupport type_;
 
@@ -79,6 +82,10 @@ private:
                 eprosima::fastdds::dds::DataReader* reader,
                 const eprosima::fastdds::dds::SubscriptionMatchedStatus& info) override;
 
+        void on_liveliness_changed(
+            eprosima::fastdds::dds::DataReader* reader,
+            const eprosima::fastdds::dds::LivelinessChangedStatus& status) override;
+
         HelloWorld hello_;
 
         int matched_;
diff --git a/examples/cpp/dds/HelloWorldExample/HelloWorld_main.cpp b/examples/cpp/dds/HelloWorldExample/HelloWorld_main.cpp
index 35870eb67..d0b912b9e 100644
--- a/examples/cpp/dds/HelloWorldExample/HelloWorld_main.cpp
+++ b/examples/cpp/dds/HelloWorldExample/HelloWorld_main.cpp
@@ -144,7 +144,8 @@ enum  optionIndex
     HELP,
     SAMPLES,
     INTERVAL,
-    ENVIRONMENT
+    ENVIRONMENT,
+    USE_ADDITIONAL_ENDPOINT
 };
 
 const option::Descriptor usage[] = {
@@ -157,6 +158,7 @@ const option::Descriptor usage[] = {
     { INTERVAL, 0, "i", "interval",          Arg::NumericRange<>,
       "  -i <num>, \t--interval=<num>  \tTime between samples in milliseconds (Default: 100)." },
     { ENVIRONMENT, 0, "e", "env",            Arg::None,       "  -e \t--env   \tLoad QoS from environment." },
+    { USE_ADDITIONAL_ENDPOINT, 0, "a", "add_endpoint", Arg::None, "  -a \t--add_endpoint   \tUse additional Reader or Writer with Topic name HelloWorldTopic_2"},
     { 0, 0, 0, 0, 0, 0 }
 };
 
@@ -188,6 +190,7 @@ int main(
     uint32_t count = 10;
     uint32_t sleep = 100;
     bool use_environment_qos = false;
+    bool use_additional_endpoint = false;
 
     argc -= (argc > 0);
     argv += (argc > 0); // skip program name argv[0] if present
@@ -289,6 +292,12 @@ int main(
         {
             use_environment_qos = true;
         }
+
+        opt = options[USE_ADDITIONAL_ENDPOINT];
+        if (opt)
+        {
+            use_additional_endpoint = true;
+        }
     }
 
     switch (type)
@@ -296,7 +305,7 @@ int main(
         case 1:
         {
             HelloWorldPublisher mypub;
-            if (mypub.init(use_environment_qos))
+            if (mypub.init(use_environment_qos, use_additional_endpoint))
             {
                 mypub.run(count, sleep);
             }
@@ -305,7 +314,7 @@ int main(
         case 2:
         {
             HelloWorldSubscriber mysub;
-            if (mysub.init(use_environment_qos))
+            if (mysub.init(use_environment_qos, use_additional_endpoint))
             {
                 mysub.run();
             }
```

### Fast DDS version/commit

2.13.0

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

_No response_

### XML configuration file

_No response_

### Relevant log output

_No response_

### Network traffic capture

_No response_

### PR DESCRIPTION
**Pull request by Mario-DL**
## Description

This PR brings a bugfix when asserting `AUTOMATIC` `MANUAL_BY_PARTICIPANT` liveliness kinds. In the scenario of having a participant with two datareaders (each of them with a lease duration of 2 secs) and other two participants with one publisher each one configured with `AUTOMATIC_LIVELINESS`. If we suddenly kill one of the publishers (network disconnection or Ctrl+C), the `on_liveliness_changed()` is not received on the reader side when we would expect it to happen (after 2 secs).

The problem stems from the fact that currently, in the reader-side participant, it is enough having an alive writer with the same kind (`AUTOMATIC_LIVELINESS`) to assert the liveliness of all of its readers with the same kind regardless of the participant.

This PR makes the liveliness assertion participant-aware by means of the `guidPrefix`. 

@Mergifyio backport 2.13.x 2.12.x 2.10.x 2.6.x

Fixes #4373 

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@mergifyio rebase

File: test/blackbox/api/dds-pim/PubSubParticipant.hpp [hunk 1]
```diff
@@ -611,6 +611,22 @@ class PubSubParticipant
...
+            class _Period
+            >
+    size_t sub_wait_liveliness_lost_for(
+            unsigned int expected_num_lost,
+            const std::chrono::duration<_Rep, _Period>& max_wait)
+    {
+        std::unique_lock<std::mutex> lock(sub_liveliness_mutex_);
+        sub_liveliness_cv_.wait_for(lock, max_wait, [this, &expected_num_lost]() -> bool
+                {
+                    return expected_num_lost == sub_times_liveliness_lost_;
```
Comment (MiguelCompany) [inline test/blackbox/api/dds-pim/PubSubParticipant.hpp:624]:
```suggestion
                    return expected_num_lost >= sub_times_liveliness_lost_;
```

File: test/blackbox/api/fastrtps_deprecated/PubSubParticipant.hpp [hunk 2]
```diff
@@ -401,6 +401,22 @@ class PubSubParticipant
...
+            class _Period
+            >
+    size_t sub_wait_liveliness_lost_for(
+            unsigned int expected_num_lost,
+            const std::chrono::duration<_Rep, _Period>& max_wait)
+    {
+        std::unique_lock<std::mutex> lock(sub_liveliness_mutex_);
+        sub_liveliness_cv_.wait_for(lock, max_wait, [this, &expected_num_lost]() -> bool
+                {
+                    return expected_num_lost == sub_times_liveliness_lost_;
```
Comment (MiguelCompany) [inline test/blackbox/api/fastrtps_deprecated/PubSubParticipant.hpp:414]:
```suggestion
                    return expected_num_lost >= sub_times_liveliness_lost_;
```

File: test/blackbox/common/BlackboxTestsLivelinessQos.cpp [hunk 3]
```diff
@@ -1946,6 +1948,54 @@ TEST(LivelinessTests, Detect_Deadlock_ManualByParticipant_Intraprocess)
...
 
+// Regression test of Refs #20584, github issue #4373
+TEST(LivelinessTests, Reader_Successfully_Asserts_Liveliness_on_a_Disconnected_Writer)
+{
+    // Create a TestTransport to simulate a network shutdown (Ctrl+C)
+    auto testTransport = std::make_shared<eprosima::fastdds::rtps::test_UDPv4TransportDescriptor>();
+
+    // Create two writer participants
+    PubSubWriter<HelloWorldPubSubType> writer_1(TEST_TOPIC_NAME);
+    PubSubWriter<HelloWorldPubSubType> writer_2(TEST_TOPIC_NAME + "2");
```
Comment (MiguelCompany) [inline test/blackbox/common/BlackboxTestsLivelinessQos.cpp:1959]: Shouldn't we check with the same topic name?

File: test/blackbox/common/BlackboxTestsLivelinessQos.cpp [hunk 4]
```diff
@@ -1946,6 +1948,54 @@ TEST(LivelinessTests, Detect_Deadlock_ManualByParticipant_Intraprocess)
...
+
+    // Create writers
+    writer_1.disable_builtin_transport()
+            .add_user_transport_to_pparams(testTransport)
+            .liveliness_lease_duration(eprosima::fastrtps::Time_t(1, 0))
+            .liveliness_kind(eprosima::fastdds::dds::AUTOMATIC_LIVELINESS_QOS)
+            .liveliness_announcement_period(eprosima::fastrtps::Time_t(0, 900000000))
+            .init();
+
+    writer_2.liveliness_lease_duration(eprosima::fastrtps::Time_t(1, 0))
```
Comment (MiguelCompany) [inline test/blackbox/common/BlackboxTestsLivelinessQos.cpp:1982]: Please ensure that the participant lease duration is greater than the liveliness lease duration. It could even be INFINITE to ensure the reader liveliness is the one being checked.

File: include/fastdds/rtps/writer/LivelinessManager.h [hunk 5]
```diff
@@ -110,7 +110,8 @@ class LivelinessManager
      * @return True if liveliness was successfully asserted
      */
     bool assert_liveliness(
-            LivelinessQosPolicyKind kind);
+            LivelinessQosPolicyKind kind,
+            GuidPrefix_t guid_prefix);
```
Comment (MiguelCompany) [inline include/fastdds/rtps/writer/LivelinessManager.h:114]: The new argument should be added to the doxygen documentation.

**Review by MiguelCompany — CHANGES_REQUESTED** [review]

File: test/blackbox/common/BlackboxTestsLivelinessQos.cpp (hunk 3 above)
Comment (Mario-DL) [reply test/blackbox/common/BlackboxTestsLivelinessQos.cpp:1959]: Not necessarily (although I think it would also work. It is enough having a pair of reader/writer matched in different participants). However I tried to stick to the scenario depicted in the issue and I think that distinguishing topic names fits better with the `PubSubPaarticipant` API so we do not try creating two topics with the same same when we `init_subscriber()`

**Review by MiguelCompany — APPROVED** [review]

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Review by MiguelCompany — APPROVED** [review]

**Comment by Mario-DL** [comment]
@richiprosima please test this

**Comment by EduPonz** [comment]
@Mergifyio rebase master

**Comment by EduPonz** [comment]
@richiprosima please test this

**Comment by EduPonz** [comment]
@Mergifyio backport 2.13.x 2.10.x 2.6.x
