### PR TITLE
Protect bitmap parsing methods <master> [9183]

### LINKED ISSUE #1337: stack-buffer-overflow was found at ./include/fastdds/rtps/messages/CDRMessage.hpp:177:21 [9133]
stack-buffer-overflow was found at ./include/fastdds/rtps/messages/CDRMessage.hpp:177:21

I used Peach Fuzzer to fuzz the DDSHelloWorldExample at ./install/fastrtps/examples/C++/DDS/HelloWorldExample/bin/DDSHelloWorldExample.
After a period of time, A stack-buffer-overflow crash was found by AddressSanitizer. Next is the full crash information.

```
=================================================================
==697665==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7f290c4d7be0 at pc 0x7f2912cf2906 bp 0x7f290c4d7b90 sp 0x7f290c4d7b88
WRITE of size 1 at 0x7f290c4d7be0 thread T4
    #0 0x7f2912cf2905 in eprosima::fastrtps::rtps::CDRMessage::readUInt32(eprosima::fastrtps::rtps::CDRMessage_t*, unsigned int*) /root/feilong/fast-dds/src/fastrtps/include/fastdds/rtps/messages/CDRMessage.hpp:177:21
    #1 0x7f2912cf2905 in eprosima::fastrtps::rtps::CDRMessage::readSequenceNumberSet(eprosima::fastrtps::rtps::CDRMessage_t*) /root/feilong/fast-dds/src/fastrtps/include/fastdds/rtps/messages/CDRMessage.hpp:242
    #2 0x7f2912ce4184 in eprosima::fastrtps::rtps::MessageReceiver::proc_Submsg_Acknack(eprosima::fastrtps::rtps::CDRMessage_t*, eprosima::fastrtps::rtps::SubmessageHeader_t*) /root/feilong/fast-dds/src/fastrtps/src/cpp/rtps/messages/MessageReceiver.cpp:922:33
    #3 0x7f2912cc28cd in eprosima::fastrtps::rtps::MessageReceiver::processCDRMsg(eprosima::fastrtps::rtps::Locator_t const&, eprosima::fastrtps::rtps::CDRMessage_t*) /root/feilong/fast-dds/src/fastrtps/src/cpp/rtps/messages/MessageReceiver.cpp:286:29
    #4 0x7f2912d00334 in eprosima::fastrtps::rtps::ReceiverResource::OnDataReceived(unsigned char const*, unsigned int, eprosima::fastrtps::rtps::Locator_t const&, eprosima::fastrtps::rtps::Locator_t const&) /root/feilong/fast-dds/src/fastrtps/src/cpp/rtps/network/ReceiverResource.cpp:105:14
    #5 0x7f2912fe8e8a in eprosima::fastdds::rtps::UDPChannelResource::perform_listen_operation(eprosima::fastrtps::rtps::Locator_t) /root/feilong/fast-dds/src/fastrtps/src/cpp/rtps/transport/UDPChannelResource.cpp:66:33
    #6 0x7f2912ff1feb in void std::_Mem_fn_base<void (eprosima::fastdds::rtps::UDPChannelResource::*)(eprosima::fastrtps::rtps::Locator_t), true>::operator()<eprosima::fastrtps::rtps::Locator_t, void>(eprosima::fastdds::rtps::UDPChannelResource*, eprosima::fastrtps::rtps::Locator_t&&) const /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/functional:600:11
    #7 0x7f2912ff1feb in void std::_Bind_simple<std::_Mem_fn<void (eprosima::fastdds::rtps::UDPChannelResource::*)(eprosima::fastrtps::rtps::Locator_t)> (eprosima::fastdds::rtps::UDPChannelResource*, eprosima::fastrtps::rtps::Locator_t)>::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/functional:1530
    #8 0x7f2912ff1feb in std::_Bind_simple<std::_Mem_fn<void (eprosima::fastdds::rtps::UDPChannelResource::*)(eprosima::fastrtps::rtps::Locator_t)> (eprosima::fastdds::rtps::UDPChannelResource*, eprosima::fastrtps::rtps::Locator_t)>::operator()() /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/functional:1520
    #9 0x7f2912ff1feb in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (eprosima::fastdds::rtps::UDPChannelResource::*)(eprosima::fastrtps::rtps::Locator_t)> (eprosima::fastdds::rtps::UDPChannelResource*, eprosima::fastrtps::rtps::Locator_t)> >::_M_run() /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/thread:115
    #10 0x7f2911075e5d  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd0e5d)
    #11 0x7f29120516b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #12 0x7f29107c14dc in clone /build/glibc-e6zv40/glibc-2.23/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Address 0x7f290c4d7be0 is located in stack of thread T4 at offset 64 in frame
    #0 0x7f2912cf1bbf in eprosima::fastrtps::rtps::CDRMessage::readSequenceNumberSet(eprosima::fastrtps::rtps::CDRMessage_t*) /root/feilong/fast-dds/src/fastrtps/include/fastdds/rtps/messages/CDRMessage.hpp:230

  This frame has 1 object(s):
    [32, 64) 'bitmap' (line 239) <== Memory access at offset 64 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
Thread T4 created by T0 here:
    #0 0x44bb2d in pthread_create /root/CL/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:317
    #1 0x7f2911075f63 in std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)()) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd0f63)

SUMMARY: AddressSanitizer: stack-buffer-overflow /root/feilong/fast-dds/src/fastrtps/include/fastdds/rtps/messages/CDRMessage.hpp:177:21 in eprosima::fastrtps::rtps::CDRMessage::readUInt32(eprosima::fastrtps::rtps::CDRMessage_t*, unsigned int*)
Shadow bytes around the buggy address:
  0x0fe5a1892f20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe5a1892f30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe5a1892f40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe5a1892f50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe5a1892f60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fe5a1892f70: 00 00 00 00 f1 f1 f1 f1 00 00 00 00[f3]f3 f3 f3
  0x0fe5a1892f80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe5a1892f90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe5a1892fa0: f1 f1 f1 f1 00 00 f2 f2 00 00 f2 f2 00 00 00 00
  0x0fe5a1892fb0: 00 00 04 f2 f2 f2 f2 f2 f8 f2 f8 f8 f8 f8 f8 f8
  0x0fe5a1892fc0: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==697665==ABORTING

```

Here is the code where the crash appeared.

```C
177    dest[i] = msg->buffer[msg->pos + i];
```

I think there may has something which has not been taken into account in security aspect.
Please check it.
Thanks very much.

## Expected Behavior

The program should not broken down during the fuzzing process.

## Current Behavior

The program broke down and AddressSanitizer printed the error information. 

## Steps to Reproduce

1.
2.
3.
4.

## System information

- Fast-RTPS version:  commit 61e907e7ab14cb5a683ba3d3be2906913a335e8b
- OS:  Ubuntu 16.04
- Network interfaces: 
                      
- ROS2: 
        

## Additional resources
- Wireshark capture 
- XML profiles file

### LINKED ISSUE #1338: stack-buffer-overflow was found at ./include/fastdds/rtps/messages/CDRMessage.hpp:134:18 [9132]
stack-buffer-overflow was found at ./include/fastdds/rtps/messages/CDRMessage.hpp:134:18

This crash is similar to issue https://github.com/eProsima/Fast-DDS/issues/1337.
But the crash position was not same.

Here is the full crash information.

```
=================================================================
==694421==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fd1b6dd80c0 at pc 0x7fd1bd5e526a bp 0x7fd1b6dd8070 sp 0x7fd1b6dd8068
WRITE of size 1 at 0x7fd1b6dd80c0 thread T4
    #0 0x7fd1bd5e5269 in eprosima::fastrtps::rtps::CDRMessage::readDataReversed(eprosima::fastrtps::rtps::CDRMessage_t*, unsigned char*, unsigned int) /root/feilong/fast-dds/src/fastrtps/include/fastdds/rtps/messages/CDRMessage.hpp:134:18
    #1 0x7fd1bd5e5269 in eprosima::fastrtps::rtps::CDRMessage::readUInt32(eprosima::fastrtps::rtps::CDRMessage_t*, unsigned int*) /root/feilong/fast-dds/src/fastrtps/include/fastdds/rtps/messages/CDRMessage.hpp:183
    #2 0x7fd1bd5e5269 in eprosima::fastrtps::rtps::CDRMessage::readSequenceNumberSet(eprosima::fastrtps::rtps::CDRMessage_t*) /root/feilong/fast-dds/src/fastrtps/include/fastdds/rtps/messages/CDRMessage.hpp:242
    #3 0x7fd1bd5d4a4b in eprosima::fastrtps::rtps::MessageReceiver::proc_Submsg_Gap(eprosima::fastrtps::rtps::CDRMessage_t*, eprosima::fastrtps::rtps::SubmessageHeader_t*) /root/feilong/fast-dds/src/fastrtps/src/cpp/rtps/messages/MessageReceiver.cpp:968:35
    #4 0x7fd1bd5b3e69 in eprosima::fastrtps::rtps::MessageReceiver::processCDRMsg(eprosima::fastrtps::rtps::Locator_t const&, eprosima::fastrtps::rtps::CDRMessage_t*) /root/feilong/fast-dds/src/fastrtps/src/cpp/rtps/messages/MessageReceiver.cpp:273:29
    #5 0x7fd1bd5f2334 in eprosima::fastrtps::rtps::ReceiverResource::OnDataReceived(unsigned char const*, unsigned int, eprosima::fastrtps::rtps::Locator_t const&, eprosima::fastrtps::rtps::Locator_t const&) /root/feilong/fast-dds/src/fastrtps/src/cpp/rtps/network/ReceiverResource.cpp:105:14
    #6 0x7fd1bd8dae8a in eprosima::fastdds::rtps::UDPChannelResource::perform_listen_operation(eprosima::fastrtps::rtps::Locator_t) /root/feilong/fast-dds/src/fastrtps/src/cpp/rtps/transport/UDPChannelResource.cpp:66:33
    #7 0x7fd1bd8e3feb in void std::_Mem_fn_base<void (eprosima::fastdds::rtps::UDPChannelResource::*)(eprosima::fastrtps::rtps::Locator_t), true>::operator()<eprosima::fastrtps::rtps::Locator_t, void>(eprosima::fastdds::rtps::UDPChannelResource*, eprosima::fastrtps::rtps::Locator_t&&) const /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/functional:600:11
    #8 0x7fd1bd8e3feb in void std::_Bind_simple<std::_Mem_fn<void (eprosima::fastdds::rtps::UDPChannelResource::*)(eprosima::fastrtps::rtps::Locator_t)> (eprosima::fastdds::rtps::UDPChannelResource*, eprosima::fastrtps::rtps::Locator_t)>::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/functional:1530
    #9 0x7fd1bd8e3feb in std::_Bind_simple<std::_Mem_fn<void (eprosima::fastdds::rtps::UDPChannelResource::*)(eprosima::fastrtps::rtps::Locator_t)> (eprosima::fastdds::rtps::UDPChannelResource*, eprosima::fastrtps::rtps::Locator_t)>::operator()() /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/functional:1520
    #10 0x7fd1bd8e3feb in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (eprosima::fastdds::rtps::UDPChannelResource::*)(eprosima::fastrtps::rtps::Locator_t)> (eprosima::fastdds::rtps::UDPChannelResource*, eprosima::fastrtps::rtps::Locator_t)> >::_M_run() /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/thread:115
    #11 0x7fd1bb967e5d  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd0e5d)
    #12 0x7fd1bc9436b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #13 0x7fd1bb0b34dc in clone /build/glibc-e6zv40/glibc-2.23/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Address 0x7fd1b6dd80c0 is located in stack of thread T4 at offset 64 in frame
    #0 0x7fd1bd5e3bbf in eprosima::fastrtps::rtps::CDRMessage::readSequenceNumberSet(eprosima::fastrtps::rtps::CDRMessage_t*) /root/feilong/fast-dds/src/fastrtps/include/fastdds/rtps/messages/CDRMessage.hpp:230

  This frame has 1 object(s):
    [32, 64) 'bitmap' (line 239) <== Memory access at offset 64 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
Thread T4 created by T0 here:
    #0 0x44bb2d in pthread_create /root/CL/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:317
    #1 0x7fd1bb967f63 in std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)()) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd0f63)

SUMMARY: AddressSanitizer: stack-buffer-overflow /root/feilong/fast-dds/src/fastrtps/include/fastdds/rtps/messages/CDRMessage.hpp:134:18 in eprosima::fastrtps::rtps::CDRMessage::readDataReversed(eprosima::fastrtps::rtps::CDRMessage_t*, unsigned char*, unsigned int)
Shadow bytes around the buggy address:
  0x0ffab6db2fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffab6db2fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffab6db2fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffab6db2ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffab6db3000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ffab6db3010: f1 f1 f1 f1 00 00 00 00[f3]f3 f3 f3 00 00 00 00
  0x0ffab6db3020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffab6db3030: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
  0x0ffab6db3040: 00 00 f2 f2 00 f2 f2 f2 00 00 00 00 00 00 04 f3
  0x0ffab6db3050: f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffab6db3060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==694421==ABORTING

```

And the code where the crash appeared:
```C
134    *(o + i) = *(msg->buffer + msg->pos + length - 1 - i);
```

## Expected Behavior

The program should not broken down during the fuzzing process.

## Current Behavior

The program broke down and AddressSanitizer printed the error information. 

## Steps to Reproduce

1.
2.
3.
4.

## System information

- Fast-RTPS version:  commit 61e907e7ab14cb5a683ba3d3be2906913a335e8b
- OS:  Ubuntu 16.04
- Network interfaces: 
                      
- ROS2: 
        

## Additional resources
- Wireshark capture 
- XML profiles file

### PR DESCRIPTION
**Pull request by MiguelCompany**
This should fix #1337 and fix #1338 

Parsing methods for sets of fragment and sequence numbers have been protected against an invalid number of bits on the bitmap.

Signed-off-by: Miguel Company <MiguelCompany@eprosima.com>

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2505/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2319/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2512/)

File: include/fastdds/rtps/messages/CDRMessage.hpp [hunk 1]
```diff
@@ -235,15 +235,23 @@ inline SequenceNumberSet_t CDRMessage::readSequenceNumberSet(
...
     uint32_t numBits = 0;
     valid &= CDRMessage::readUInt32(msg, &numBits);
-    uint32_t n_longs = (numBits + 31ul) / 32ul;
-    uint32_t bitmap[8];
-    for (uint32_t i = 0; i < n_longs; ++i)
+    if (numBits > 256u)
     {
-        valid &= CDRMessage::readUInt32(msg, &bitmap[i]);
+        sns.base(c_SequenceNumber_Unknown);
+        valid = false;
```
Comment (IkerLuengo) [inline include/fastdds/rtps/messages/CDRMessage.hpp:241]: We can make `valid` local to the `else` clause, as it is not used anywhere else.

**Review by IkerLuengo — CHANGES_REQUESTED** [review]
Apart from the linter errors, a minor cosmetic change.
CI errors don't seem to be related to the change.

File: include/fastdds/rtps/messages/CDRMessage.hpp (hunk 1 above)
Comment (MiguelCompany) [reply include/fastdds/rtps/messages/CDRMessage.hpp:241]: No. What we should do is to check it along with the check on the number of bits.

Comment (MiguelCompany) [reply include/fastdds/rtps/messages/CDRMessage.hpp]: Done in 590b690dc5d68e07cbefeea8ef6d17282d39c2af

**Comment by MiguelCompany** [comment]
Uncrustify has already been solved on #1361

**Review by IkerLuengo — DISMISSED** [review]
:+1:

**Review by IkerLuengo — APPROVED** [review]
LGTM

**Review by IkerLuengo — APPROVED** [review]
:facepalm:  :+1:

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2558/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2368/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2565/)
