### PR TITLE
[22756] Fix error handling logic in `try_setting_buffer_size`

### LINKED ISSUE #4684: [22208] The SocketTransportDescriptor::min_send_buffer_size() method returns too large value when exceeded net.core.wmem_max
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

The values `sendBufferSize` and `receiveBufferSize` from the `SocketTransportDescriptor` adequately reflect the buffer sizes of the created UDP sockets.

### Current behavior

The values `sendBufferSize` and `receiveBufferSize` from the `SocketTransportDescriptor` and `SocketTransportDescriptor::min_send_buffer_size()` method return larger values than the actual size of the UDP socket buffers.

### Steps to reproduce

Using the  fields `sendBufferSize` and `receiveBufferSize` from the `SocketTransportDescriptor` , you must set a value greater than **net.core.wmem_max** or **net.core.rmem_max**.

### Fast DDS version/commit

v2.13.0

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

UDPv4

### Additional context

_No response_

### XML configuration file

_No response_

### Relevant log output

_No response_

### Network traffic capture

_No response_

### PR DESCRIPTION
**Pull request by MiguelCompany**
## Description

This should fix #4684 by applying the last suggested changes

@Mergifyio backport 3.1.x 3.0.x 2.14.x 2.10.x

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- __NO__: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_: Any new/modified methods have been properly documented using Doxygen. 
- _N/A_: Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [x] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [x] Changes are API compatible. 
- _N/A_: New feature has been added to the `versions.md` file (if applicable).
- _N/A_: New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [ ] If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

File: src/cpp/rtps/transport/asio_helpers.hpp [hunk 1]
```diff
@@ -87,11 +87,11 @@ struct asio_helpers
             // Last attempt was successful. Get the actual value set.
             BufferOptionType option;
             socket.get_option(option, ec);
-            if (!ec)
+            if (!ec && (option.value() >= value_to_set))
```
Comment (juanlofer-eprosima) [inline src/cpp/rtps/transport/asio_helpers.hpp:90]: Super NIT: I wonder if it's possible that set results in a value greater than the one specified. I guess not, but if that was the case maybe we should fail? Or add an extra check that the value isn't greater than `initial_buffer_value`.

**Review by juanlofer-eprosima — CHANGES_REQUESTED** [review]

File: src/cpp/rtps/transport/asio_helpers.hpp (hunk 1 above)
Comment (MiguelCompany) [reply src/cpp/rtps/transport/asio_helpers.hpp]: 2eec3ba

**Review by juanlofer-eprosima — APPROVED** [review]
LGTM

**Review by juanlofer-eprosima — APPROVED** [review]

**Comment by MiguelCompany** [comment]
@Mergifyio backport 3.1.x 3.0.x 2.14.x 2.10.x
