### PR TITLE
[21065] Bugfix: correct liveliness state in a multiple reader - one writer scenario

### LINKED ISSUE #4610: Incorrect state of Liveliness of Readers who accept data from a single Writer
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

The correctness of the Liveliness of Readers should not depend on their number.

### Current behavior

Incorrect state of Liveliness of Readers who accept data from a single Writer

### Steps to reproduce

Developed a test based on the HelloWorldExample code in accordance with the attached patch. In the HelloWorldExample on the subscriber's side, another Reader of the existing HelloWorldTopic was simply added.
To repeat this situation, you need to open two terminals and perform the following sequence of actions.
1. In terminal 1, execute `./DDSHelloWorldExample publisher -s 0 -i 2000`
2. In terminal 2, execute `./DDSHelloWorldExample subscriber`
3. As a result, two Readers switch to the Alive Liveliness state and accept the Topic from the Writer (see the timestamp 10031.383 on the log below)
4. Pressing Enter ends the Publisher's work in the first terminal
5. At time 10036.566, incorrect behavior is observed - the callback for the Reader 0x5c3278c143c0 was not called.  At the same time, the  Reader 0x5c3278c88670 behaves correctly:  `alive_count=0 not_alive_count=0 alive_count_change=-1 not_alive_count_change=0`
6. In terminal 1, execute `./DDSHelloWorldExample publisher -s 0 -i 2000`
7. At time 10044.605 the Reader 0x5c3278c143c0 has an incorrect  state `alive_count=2 not_alive_count=0 alive_count_change=1 not_alive_count_change=0` instead `alive_count=1 not_alive_count=0 alive_count_change=1 not_alive_count_change=0`
8. Pressing \<Ctrl-C\> ends the Publisher's work in the first terminal
9. At time 10051.306 the Reader 0x5c3278c143c0 has an incorrect  state `alive_count=1 not_alive_count=1 alive_count_change=-1 not_alive_count_change=1` instead `alive_count=0 not_alive_count=1 alive_count_change=-1 not_alive_count_change=1`
10. After 20 seconds (timestamp 10069.707), the Participant timeout is triggered - the Reader's 0x5c3278c143c0 callback is not called. This is incorrect.
11. In terminal 1, execute `./DDSHelloWorldExample publisher -s 0 -i 2000`
12. At time 10077.248 the Reader 0x5c3278c143c0 has an incorrect  state `alive_count=2 not_alive_count=1 alive_count_change=1 not_alive_count_change=0` instead `alive_count=1 not_alive_count=0 alive_count_change=1 not_alive_count_change=0`

Log from terminal 2:
```
Starting 
Reader 0x5c3278c143c0 for topic HelloWorldTopic has been created.
Reader 0x5c3278c88670 for topic HelloWorldTopic has been created.
Subscriber running. Please press enter to stop the Subscriber
10031.374 s: Reader 0x5c3278c143c0 matched.
10031.374 s: Reader 0x5c3278c88670 matched.
10031.383 s: on_liveliness_changed() called for Reader 0x5c3278c143c0 alive_count=1 not_alive_count=0 alive_count_change=1 not_alive_count_change=0 last_publication_handle=1.f.f7.f3.2a.57.5d.18.0.0.0.0.0.0.1.3
10031.383 s: on_liveliness_changed() called for Reader 0x5c3278c88670 alive_count=1 not_alive_count=0 alive_count_change=1 not_alive_count_change=0 last_publication_handle=1.f.f7.f3.2a.57.5d.18.0.0.0.0.0.0.1.3
10032.565 s: Reader 0x5c3278c88670 receive message: HelloWorld 3 RECEIVED
10032.566 s: Reader 0x5c3278c143c0 receive message: HelloWorld 3 RECEIVED
10034.565 s: Reader 0x5c3278c88670 receive message: HelloWorld 4 RECEIVED
10034.565 s: Reader 0x5c3278c143c0 receive message: HelloWorld 4 RECEIVED
10036.566 s: Reader 0x5c3278c143c0 unmatched.
10036.566 s: on_liveliness_changed() called for Reader 0x5c3278c88670 alive_count=0 not_alive_count=0 alive_count_change=-1 not_alive_count_change=0 last_publication_handle=1.f.f7.f3.2a.57.5d.18.0.0.0.0.0.0.1.3
10036.566 s: Reader 0x5c3278c88670 unmatched.
10043.705 s: Reader 0x5c3278c143c0 matched.
10043.705 s: Reader 0x5c3278c88670 matched.
10044.605 s: on_liveliness_changed() called for Reader 0x5c3278c143c0 alive_count=2 not_alive_count=0 alive_count_change=1 not_alive_count_change=0 last_publication_handle=1.f.f7.f3.3d.57.f0.2a.0.0.0.0.0.0.1.3
10044.605 s: on_liveliness_changed() called for Reader 0x5c3278c88670 alive_count=1 not_alive_count=0 alive_count_change=1 not_alive_count_change=0 last_publication_handle=1.f.f7.f3.3d.57.f0.2a.0.0.0.0.0.0.1.3
10045.706 s: Reader 0x5c3278c88670 receive message: HelloWorld 2 RECEIVED
10045.706 s: Reader 0x5c3278c143c0 receive message: HelloWorld 2 RECEIVED
10047.706 s: Reader 0x5c3278c88670 receive message: HelloWorld 3 RECEIVED
10047.706 s: Reader 0x5c3278c143c0 receive message: HelloWorld 3 RECEIVED
10049.706 s: Reader 0x5c3278c88670 receive message: HelloWorld 4 RECEIVED
10049.706 s: Reader 0x5c3278c143c0 receive message: HelloWorld 4 RECEIVED
10051.306 s: on_liveliness_changed() called for Reader 0x5c3278c143c0 alive_count=1 not_alive_count=1 alive_count_change=-1 not_alive_count_change=1 last_publication_handle=1.f.f7.f3.3d.57.f0.2a.0.0.0.0.0.0.1.3
10051.306 s: on_liveliness_changed() called for Reader 0x5c3278c88670 alive_count=0 not_alive_count=1 alive_count_change=-1 not_alive_count_change=1 last_publication_handle=1.f.f7.f3.3d.57.f0.2a.0.0.0.0.0.0.1.3
10069.707 s: Reader 0x5c3278c143c0 unmatched.
10069.707 s: on_liveliness_changed() called for Reader 0x5c3278c88670 alive_count=0 not_alive_count=0 alive_count_change=0 not_alive_count_change=-1 last_publication_handle=1.f.f7.f3.3d.57.f0.2a.0.0.0.0.0.0.1.3
10069.707 s: Reader 0x5c3278c88670 unmatched.
10076.348 s: Reader 0x5c3278c143c0 matched.
10076.348 s: Reader 0x5c3278c88670 matched.
10077.248 s: on_liveliness_changed() called for Reader 0x5c3278c143c0 alive_count=2 not_alive_count=1 alive_count_change=1 not_alive_count_change=0 last_publication_handle=1.f.f7.f3.48.57.9c.81.0.0.0.0.0.0.1.3
10077.248 s: on_liveliness_changed() called for Reader 0x5c3278c88670 alive_count=1 not_alive_count=0 alive_count_change=1 not_alive_count_change=0 last_publication_handle=1.f.f7.f3.48.57.9c.81.0.0.0.0.0.0.1.3
10078.348 s: Reader 0x5c3278c88670 receive message: HelloWorld 2 RECEIVED
10078.348 s: Reader 0x5c3278c143c0 receive message: HelloWorld 2 RECEIVED
10080.349 s: Reader 0x5c3278c88670 receive message: HelloWorld 3 RECEIVED
10080.349 s: Reader 0x5c3278c143c0 receive message: HelloWorld 3 RECEIVED
```
HelloWorld example code patch:
```
diff --git a/examples/cpp/dds/HelloWorldExample/HelloWorldPublisher.cpp b/examples/cpp/dds/HelloWorldExample/HelloWorldPublisher.cpp
index 86f3e0009..28a8aca15 100644
--- a/examples/cpp/dds/HelloWorldExample/HelloWorldPublisher.cpp
+++ b/examples/cpp/dds/HelloWorldExample/HelloWorldPublisher.cpp
@@ -107,6 +107,10 @@ bool HelloWorldPublisher::init(
         publisher_->get_default_datawriter_qos(wqos);
     }
 
+    wqos.liveliness().kind = AUTOMATIC_LIVELINESS_QOS;
+    wqos.liveliness().lease_duration = eprosima::fastrtps::Time_t(1, 000000000);
+    wqos.liveliness().announcement_period = eprosima::fastrtps::Time_t(0, 900000000);
+
     writer_ = publisher_->create_datawriter(
         topic_,
         wqos,
diff --git a/examples/cpp/dds/HelloWorldExample/HelloWorldSubscriber.cpp b/examples/cpp/dds/HelloWorldExample/HelloWorldSubscriber.cpp
index 6823a32f4..29c96a872 100644
--- a/examples/cpp/dds/HelloWorldExample/HelloWorldSubscriber.cpp
+++ b/examples/cpp/dds/HelloWorldExample/HelloWorldSubscriber.cpp
@@ -32,11 +32,23 @@
 
 using namespace eprosima::fastdds::dds;
 
+std::string get_time()
+{
+    using namespace std::chrono;
+
+    auto t = (duration_cast<duration<double>>(steady_clock::now().time_since_epoch())).count();
+    
+    char buf[256];
+    std::snprintf(buf, sizeof(buf), "%.3f s: ", t);
+    return buf;
+}
+
 HelloWorldSubscriber::HelloWorldSubscriber()
     : participant_(nullptr)
     , subscriber_(nullptr)
     , topic_(nullptr)
     , reader_(nullptr)
+    , reader_2_(nullptr)
     , type_(new HelloWorldPubSubType())
 {
 }
@@ -106,12 +118,24 @@ bool HelloWorldSubscriber::init(
         subscriber_->get_default_datareader_qos(rqos);
     }
 
+    rqos.liveliness().lease_duration = eprosima::fastrtps::Time_t(1, 600000000);
     reader_ = subscriber_->create_datareader(topic_, rqos, &listener_);
 
     if (reader_ == nullptr)
     {
         return false;
     }
+    std::cout << "Reader " << reader_ << " for topic " << 
+            reader_->get_topicdescription()->get_name() << " has been created." << std::endl;
+
+    reader_2_ = subscriber_->create_datareader(topic_, rqos, &listener_);
+
+    if (reader_2_ == nullptr)
+    {
+        return false;
+    }
+    std::cout << "Reader " << reader_2_ << " for topic " << 
+            reader_2_->get_topicdescription()->get_name() << " has been created." << std::endl;
 
     return true;
 }
@@ -122,6 +146,10 @@ HelloWorldSubscriber::~HelloWorldSubscriber()
     {
         subscriber_->delete_datareader(reader_);
     }
+    if (reader_2_ != nullptr)
+    {
+        subscriber_->delete_datareader(reader_2_);
+    }
     if (topic_ != nullptr)
     {
         participant_->delete_topic(topic_);
@@ -134,18 +162,18 @@ HelloWorldSubscriber::~HelloWorldSubscriber()
 }
 
 void HelloWorldSubscriber::SubListener::on_subscription_matched(
-        DataReader*,
+        DataReader* reader,
         const SubscriptionMatchedStatus& info)
 {
     if (info.current_count_change == 1)
     {
         matched_ = info.total_count;
-        std::cout << "Subscriber matched." << std::endl;
+        std::cout << get_time() << "Reader " << reader << " matched." << std::endl;
     }
     else if (info.current_count_change == -1)
     {
         matched_ = info.total_count;
-        std::cout << "Subscriber unmatched." << std::endl;
+        std::cout << get_time() << "Reader " << reader << " unmatched." << std::endl;
     }
     else
     {
@@ -164,11 +192,25 @@ void HelloWorldSubscriber::SubListener::on_data_available(
         {
             samples_++;
             // Print your structure data here.
-            std::cout << "Message " << hello_.message() << " " << hello_.index() << " RECEIVED" << std::endl;
+            std::cout << get_time() << "Reader " << reader << " receive message: " << 
+                    hello_.message() << " " << hello_.index() << " RECEIVED" << std::endl;
         }
     }
 }
 
+void HelloWorldSubscriber::SubListener::on_liveliness_changed(
+        eprosima::fastdds::dds::DataReader* reader,
+        const eprosima::fastdds::dds::LivelinessChangedStatus& status)
+{
+    std::cout << get_time() << "on_liveliness_changed() called" << 
+        " for Reader " << reader <<
+        " alive_count=" << status.alive_count <<
+        " not_alive_count=" << status.not_alive_count << 
+        " alive_count_change=" << status.alive_count_change << 
+        " not_alive_count_change=" << status.not_alive_count_change << 
+        " last_publication_handle=" << status.last_publication_handle << "\n";
+}
+
 void HelloWorldSubscriber::run()
 {
     std::cout << "Subscriber running. Please press enter to stop the Subscriber" << std::endl;
diff --git a/examples/cpp/dds/HelloWorldExample/HelloWorldSubscriber.h b/examples/cpp/dds/HelloWorldExample/HelloWorldSubscriber.h
index ecd897bd5..c6ab96615 100644
--- a/examples/cpp/dds/HelloWorldExample/HelloWorldSubscriber.h
+++ b/examples/cpp/dds/HelloWorldExample/HelloWorldSubscriber.h
@@ -55,6 +55,7 @@ private:
     eprosima::fastdds::dds::Topic* topic_;
 
     eprosima::fastdds::dds::DataReader* reader_;
+    eprosima::fastdds::dds::DataReader* reader_2_;
 
     eprosima::fastdds::dds::TypeSupport type_;
 
@@ -79,6 +80,10 @@ private:
                 eprosima::fastdds::dds::DataReader* reader,
                 const eprosima::fastdds::dds::SubscriptionMatchedStatus& info) override;
 
+        void on_liveliness_changed(
+            eprosima::fastdds::dds::DataReader* reader,
+            const eprosima::fastdds::dds::LivelinessChangedStatus& status) override;
+
         HelloWorld hello_;
 
         int matched_;
```

### Fast DDS version/commit

2.13.0

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

_No response_

### XML configuration file

_No response_

### Relevant log output

_No response_

### Network traffic capture

_No response_

### PR DESCRIPTION
**Pull request by Mario-DL**
## Description

This PR corrects a misbehavior given in a single writer - multiple readers scenario. When the writer is destroyed, the `WriterProxy` is removed from readers. When it is removed from the first one, the `LivelinessManager::remove_writer()` returns `false` as `--writer.count` is `1`, hence the `liveliness_changed` callback is not triggered (`callback_` within `LivelinessManager` is not invoked). When the `WriterProxy` is deleted from the second reader, the `LivelinessManager::remove_writer()` correctly removes the writer and fires the `callback`. The problem in this case is that, later, in `WLP::sub_liveliness_changed()` the `update_liveliness_changed_status()` is only called for this later reader, since the first one is not matched anymore and `reader->matched_writer_is_matched()` returns `false`, corrupting its liveliness state. In this situation, if the writer wakes up again, the first reader is going to return an `alive_count` of `2` instead of `1`.

The fix proposes that every time we unpair a `WriterProxy` from a reader, we should also update the liveliness state for that particular reader. The solution tries to avoid defining extra collections for tracking readers/writers.

@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x

Fixes #4610  

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- __NO__ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [X] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [X] Changes are API compatible. 
- __NO__ New feature has been added to the `versions.md` file (if applicable).
- __NO__ New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@richiprosima Please test_3 this

File: src/cpp/rtps/writer/LivelinessManager.hpp [hunk 1]
```diff
@@ -82,15 +82,17 @@ class LivelinessManager
 
     /**
      * @brief Removes a writer
-     * @param guid GUID of the writer
-     * @param kind Liveliness kind
-     * @param lease_duration Liveliness lease duration
+     * @param [in] guid GUID of the writer
+     * @param [in] kind Liveliness kind
+     * @param [in] lease_duration Liveliness lease duration
+     * @param [in,out] writer_liveliness_status The liveliness status of the writer
```
Comment (MiguelCompany) [inline src/cpp/rtps/writer/LivelinessManager.hpp:88]:
```suggestion
     * @param [out] writer_liveliness_status The liveliness status of the writer
```

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
Just a small nit, can be applied without running CI again

**Comment by MiguelCompany** [comment]
@richiprosima Please test_3 linux

**Review by MiguelCompany — APPROVED** [review]

**Comment by MiguelCompany** [comment]
@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x
