### PR TITLE
[19347] Fix encapsulation format in WLP

### LINKED ISSUE #3782: [19347] Wrong encapsulation in ParticipantMessageData header
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Currently, wlp data declares its serialization method as plcdr during the serialization process, but actually the serialization method is in accordance with cdr. Is this part of the description wrong?

https://github.com/eProsima/Fast-DDS/blob/f7d77cfb29bf79ad08022e67d5eb4cb58a1d71dd/src/cpp/rtps/builtin/liveliness/WLP.cpp#L905

### PR DESCRIPTION
**Pull request by EduPonz**
## Description

As #3782 points out, the encapsulation used for the ParticipantMessageData messages within the WLP was not correctly set. This PR:
* Sets the encapsulation to `CDR`
* Extends validation of WLP messages
* Fixes #3782 

@Mergifyio backport 2.11.x 2.10.x 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- *N/A*: New feature has been added to the `versions.md` file (if applicable).
- *N/A*: New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by EduPonz** [comment]
@richiprosima please test this

**Comment by EduPonz** [comment]
@richiprosima please test mac

File: src/cpp/rtps/builtin/liveliness/WLPListener.cpp [hunk 1]
```diff
@@ -74,22 +74,28 @@ void WLPListener::onNewCacheChangeAdded(
...
     {
-        if (PL_CDR_BE == change->serializedPayload.data[1])
+        // Encapsulation in the second byte of the representation header.
+        change->serializedPayload.encapsulation = (uint16_t)change->serializedPayload.data[1];
+
+        // Extract GuidPrefix
+        memcpy(guidP.value, change->serializedPayload.data + 4, 12);
+
+        // Extract liveliness kind
+        if (is_wlp_kind(&change->serializedPayload.data[16]))
```
Comment (MiguelCompany) [inline src/cpp/rtps/builtin/liveliness/WLPListener.cpp:88]: Would be better if this method has an output argument that returns the liveliness kind.
We would then only have the failing validation condition:

```
if (!get_wlp_kind(&change->serializedPayload.data[16], livelinessKind))
{
    // logInfo + remove_change + return
}
```

File: src/cpp/rtps/builtin/liveliness/WLPListener.cpp [hunk 2]
```diff
@@ -130,12 +138,17 @@ bool WLPListener::separateKey(
...
-    for (uint8_t i = 0; i < 12; ++i)
+    bool ret = false;
+    if (is_wlp_kind(&key.value[12]))
     {
-        guidP->value[i] = key.value[i];
+        // Extract GuidPrefix
+        memcpy(guidP->value, key.value, 12);
+
+        // Extract liveliness kind
+        *liveliness = (LivelinessQosPolicyKind)key.value[15];
```
Comment (MiguelCompany) [inline src/cpp/rtps/builtin/liveliness/WLPListener.cpp:148]: We should also subtract 1 here.

**Review by MiguelCompany — CHANGES_REQUESTED** [review]

**Comment by EduPonz** [comment]
@richiware please test this

**Comment by EduPonz** [comment]
@richiprosima please test this

**Comment by EduPonz** [comment]
@richiprosima please test this

File: include/fastdds/rtps/builtin/liveliness/WLPListener.h [hunk 3]
```diff
@@ -86,15 +86,17 @@ class WLPListener : public ReaderListener
...
+     * @param[in] serialized_kind A pointer to the first octet of the kind array. The function assumes 4 elements
      *        in the array.
+     * @param[out] liveliness_kind A reference to the LivelinessQosPolicyKind.
      *
      * @return True if the kind corresponds with one for WLP, false otherwise.
      */
-    bool is_wlp_kind(
-            octet* kind);
+    bool get_wlp_kind(
+            octet* serialized_kind,
```
Comment (MiguelCompany) [inline include/fastdds/rtps/builtin/liveliness/WLPListener.h:98]:
```suggestion
            const octet* serialized_kind,
```

File: src/cpp/rtps/builtin/liveliness/WLPListener.cpp [hunk 4]
```diff
@@ -75,28 +75,51 @@ void WLPListener::onNewCacheChangeAdded(
         }
     }
 
-    // Data should have at least 4 bytes of representation header, 12 of GuidPrefix, and 4 of kind.
-    if (change->serializedPayload.length >= 20)
+    // Serialized payload should have at least 4 bytes of representation header, 12 of GuidPrefix,
+    // 4 of kind, and 4 of length.
+    const uint32_t representation_header_size = 4;
+    const uint32_t guid_prefix_size = 12;
```
Comment (MiguelCompany) [inline src/cpp/rtps/builtin/liveliness/WLPListener.cpp:81]: We already have constants for these two

File: src/cpp/rtps/builtin/liveliness/WLPListener.cpp [hunk 5]
```diff
@@ -75,28 +75,51 @@ void WLPListener::onNewCacheChangeAdded(
...
+    const uint32_t participant_msg_data_kind_size = 4;
+    const uint32_t participant_msg_data_length_size = 4;
+    const uint32_t min_serialized_length = representation_header_size
```
Comment (MiguelCompany) [inline src/cpp/rtps/builtin/liveliness/WLPListener.cpp:84]: I would use constexpr instead of const

File: src/cpp/rtps/builtin/liveliness/WLPListener.cpp [hunk 6]
```diff
@@ -75,28 +75,51 @@ void WLPListener::onNewCacheChangeAdded(
...
+        // Create CDR message from buffer to deserialize contents for further validation
+        CDRMessage_t cdr_message(change->serializedPayload);
+
+        bool message_ok = (
+            // Skip representation header
+            CDRMessage::skip(&cdr_message, representation_header_size)
+            // Extract GuidPrefix
+            && CDRMessage::readData(&cdr_message, guidP.value, guid_prefix_size)
+            // Skip kind, it will be validated later
+            && CDRMessage::skip(&cdr_message, participant_msg_data_length_size)
```
Comment (MiguelCompany) [inline src/cpp/rtps/builtin/liveliness/WLPListener.cpp:104]:
```suggestion
            && CDRMessage::skip(&cdr_message, participant_msg_data_kind_size)
```

File: src/cpp/rtps/builtin/liveliness/WLPListener.cpp [hunk 7]
```diff
@@ -75,28 +75,51 @@ void WLPListener::onNewCacheChangeAdded(
...
     {
-        // Encapsulation in the second byte of the representation header.
-        change->serializedPayload.encapsulation = (uint16_t)change->serializedPayload.data[1];
-
-        // Extract GuidPrefix
-        memcpy(guidP.value, change->serializedPayload.data + 4, 12);
-
-        // Extract liveliness kind
-        if (is_wlp_kind(&change->serializedPayload.data[16]))
+        const uint32_t participant_msg_data_pos = 16;
```
Comment (MiguelCompany) [inline src/cpp/rtps/builtin/liveliness/WLPListener.cpp:91]:
```suggestion
        const uint32_t participant_msg_data_kind_pos = 16;
```

File: src/cpp/rtps/builtin/liveliness/WLPListener.cpp [hunk 8]
```diff
@@ -75,28 +75,51 @@ void WLPListener::onNewCacheChangeAdded(
...
+        const uint32_t encapsulation_pos = 16;
```
Comment (MiguelCompany) [inline src/cpp/rtps/builtin/liveliness/WLPListener.cpp:92]:
```suggestion
        const uint32_t encapsulation_pos = 1;
```

File: src/cpp/rtps/builtin/liveliness/WLPListener.cpp [hunk 9]
```diff
@@ -75,28 +75,51 @@ void WLPListener::onNewCacheChangeAdded(
...
+            && CDRMessage::readUInt32(&cdr_message, &data_length)
+            // Check that serialized length is correctly set
+            && (change->serializedPayload.length >= min_serialized_length + data_length));
+
+        if (message_ok)
         {
-            // Adjust and cast to LivelinessQosPolicyKind enum, where AUTOMATIC_LIVELINESS_QOS == 0
-            livelinessKind = (LivelinessQosPolicyKind)(change->serializedPayload.data[19] - 0x01);
+            // Extract encapsulation from the second byte of the representation header.
+            change->serializedPayload.encapsulation = (uint16_t)change->serializedPayload.data[encapsulation_pos];
```
Comment (MiguelCompany) [inline src/cpp/rtps/builtin/liveliness/WLPListener.cpp:115]: Assign encapsulation before deserializing

**Review by MiguelCompany — CHANGES_REQUESTED** [review]

**Review by MiguelCompany — APPROVED** [review]

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by EduPonz** [comment]
@Mergifyio backport 2.11.x 2.10.x 2.6.x
