### PR TITLE
[22704] Support compiler MSYS2-MinGW

### LINKED ISSUE #5575: [22704] Link problem with MinGW
### Is there an already existing issue for this?

- [x] I have searched the existing issues

### Expected behavior

I have already compile foonathan_memory, fastcdr and tinyxml2 with MinGW successfully. But there are some problem when I compile the fastdds with MinGW, like "i64 to LL","stat redefined","declspec( dllexport )  to __attribute__((visibility("default")))"...... I used some special means to solve these problems and finally successfully compiled fastdds, then i  got libfastdds.dll and libfastdds.dll.a

### Current behavior

But when I use libfastdds.dll and libfastdds.dll.a in my project, there are some thing wrong like
`E:/mingw32-14/bin/../lib/gcc/i686-w64-mingw32/14.2.0/../../../../i686-w64-mingw32/bin/ld.exe: CMakeFiles\MBus.dir/objects.a(startlogPubSubTypes.cxx.obj):startlogPubSubTypes.cxx:(.text+0x5cd): undefined reference to `eprosima::fastdds::MD5::MD5()'`......
All the symbol from FastDDS which i used in my project was undefined. I tried every import and export combination in fastdds_dll.hpp, "__attribute__((visibility("default")))" "declspec( dllexport )" "declspec( dllimport )" "null" . But does not work.
Are there some special export config for MinGW in FastDDS?

### Steps to reproduce

1:Compile foonathan_memory, fastcdr and tinyxml2 with MinGW.
2:Modify the source code, like modify CMAKE_CXX_FLAGS, modify include in some files, and so on.
3:Use libfastdds.dll.a in your project.

### Fast DDS version/commit

FastDDS v3.1.1 master
FastCDR v2.2.5 
MinGW  v14.2.0
Windows10

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

_No response_

### XML configuration file

_No response_

### Relevant log output

_No response_

### Network traffic capture

_No response_

### PR DESCRIPTION
**Pull request by RookieCLY**
Support compilation using MinGW. Version: MSYS2-MinGW-V14.2, x86_64-w64-mingw32.

## Description

1. The ‘COMPILE_TOOLS’ compilation option is turned off when compiling with MinGW because there are still some issues that have not been resolved here, but it does not affect the use of the main body of fastdds.
2. The import and export settings in thefastdds_dll.hpp file were changed to adapt to the symbol import and export rules of mingw. Tests found that these changes were effective.
3. The macro definition 'MINGW_COMPILER' has been added in cmakelists.txt to control some code to move towards new branches, which are used to resolve library dependency differences between compilers.
4. Some compile-time warnings that do not affect use have been canceled. 'ws2_32' and 'mswsock' libraries have been manually linked. The above changes are written in cmakelists.txt and will only take effect when the compiler is MinGW.
5. Almost all changes only take effect when the compiler is MinGW. Before compiling Fast-DDS with MinGW, it was best to use MinGW to compile its dependent libraries, such as fastcdr, tinyxml2 and foonathan_memory.

@Mergifyio backport 3.1.x 3.0.x 2.14.x 2.10.x

Fixes #5575 

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [x] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [x] Changes are API compatible. 
- _N/A_New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- _N/A_ Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [ ] If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

File: src/cpp/fastdds/xtypes/serializers/json/dynamic_data_json.cpp [hunk 1]
```diff
@@ -744,9 +746,20 @@ ReturnCode_t json_serialize_basic_member(
             if (RETCODE_OK == ret)
             {
                 // Insert UTF-8 converted value
+#if defined(MINGW_COMPILER)
+                std::wstring aux_wstring_value({value});
+                std::string utf8_value;
+                int size_needed = std::wcstombs(nullptr, aux_wstring_value.data(), 0);
+                if (size_needed > 0) {
```
Comment (Javgilavi) [inline src/cpp/fastdds/xtypes/serializers/json/dynamic_data_json.cpp:753]:
```suggestion
                if (size_needed > 0) 
                {
```

File: src/cpp/fastdds/xtypes/serializers/json/dynamic_data_json.cpp [hunk 2]
```diff
@@ -776,8 +789,17 @@ ReturnCode_t json_serialize_basic_member(
             if (RETCODE_OK == ret)
             {
                 // Insert UTF-8 converted value
+#ifdef MINGW_COMPILER
+                std::string utf8_value;
+                int size_needed = std::wcstombs(nullptr, value.data(), 0);
+                if (size_needed > 0) {
```
Comment (Javgilavi) [inline src/cpp/fastdds/xtypes/serializers/json/dynamic_data_json.cpp:795]:
```suggestion
                if (size_needed > 0) 
                {
```

File: src/cpp/utils/SystemInfo.cpp [hunk 3]
```diff
@@ -155,9 +155,17 @@ fastdds::dds::ReturnCode_t SystemInfo::get_username(
 bool SystemInfo::file_exists(
         const std::string& filename)
 {
+#ifdef _WIN32
+    // modify for mingw
+    DWORD fileAttributes = GetFileAttributesA(filename.c_str());
+    if (fileAttributes == INVALID_FILE_ATTRIBUTES) {
```
Comment (Javgilavi) [inline src/cpp/utils/SystemInfo.cpp:161]:
```suggestion
    if (fileAttributes == INVALID_FILE_ATTRIBUTES) 
    {
```

File: src/cpp/utils/SystemInfo.cpp [hunk 4]
```diff
@@ -155,9 +155,17 @@ fastdds::dds::ReturnCode_t SystemInfo::get_username(
...
+        return false;
+    }
+    return !(fileAttributes & FILE_ATTRIBUTE_DIRECTORY);
+#else
     struct stat s;
-    // Check existence and that it is a regular file (and not a folder)
     return (stat(filename.c_str(), &s) == 0 && s.st_mode & S_IFREG);
+#endif
```
Comment (Javgilavi) [inline src/cpp/utils/SystemInfo.cpp:168]:
```suggestion
#endif // ifdef _WIN32
```

File: src/cpp/utils/TimedConditionVariable.cpp [hunk 5]
```diff
@@ -50,9 +50,15 @@
...
-#define w2ux 116444736000000000i64     //1.jan1601 to 1.jan1970
+#ifdef MINGW_COMPILER
+    #define exp7           10000000LL     //1E+7     //C-file part
+    #define exp9         1000000000LL     //1E+9
+    #define w2ux 116444736000000000LL     //1.jan1601 to 1.jan1970
+#else
+    #define exp7           10000000i64     //1E+7     //C-file part
+    #define exp9         1000000000i64     //1E+9
+    #define w2ux 116444736000000000i64     //1.jan1601 to 1.jan1970
+#endif
```
Comment (Javgilavi) [inline src/cpp/utils/TimedConditionVariable.cpp:61]:
```suggestion
#endif // ifdef MINGW_COMPILER
```

**Review by Javgilavi — COMMENTED** [review]
The pull request looks great overall! 
Could you please make a few minor adjustments to align it with our uncrustify style guidelines so that it passes our CI checks?

**Comment by RookieCLY** [comment]
Hi, @Javgilavi . Thanks for the advice, I will do it soon. By the way, are there any other advice for the CI checks, like DCO and so on?

**Comment by Javgilavi** [comment]
Hi @RookieCLY,

Thanks for asking! I was actually about to mention the DCO issue, so you beat me to it.

In the CI output, you can click on the [DCO Details](https://github.com/eProsima/Fast-DDS/pull/5600/checks?check_run_id=36160304523) link, which provides clear instructions on how to fix the problem. Essentially, you need to sign off your commits. Everything you need is explained in that section.

If you have any further questions or need additional help, feel free to ask.

File: src/cpp/fastdds/xtypes/serializers/json/dynamic_data_json.cpp (hunk 1 above)
Comment (Javgilavi) [inline src/cpp/fastdds/xtypes/serializers/json/dynamic_data_json.cpp:753]: You forget this change. Also, don't add empty spaces after the line
```suggestion
                if (size_needed > 0)
                {
```

File: src/cpp/fastdds/xtypes/serializers/json/dynamic_data_json.cpp [hunk 6]
```diff
@@ -744,9 +746,20 @@ ReturnCode_t json_serialize_basic_member(
...
+                    utf8_value.resize(size_needed);
+                    std::wcstombs(&utf8_value[0], aux_wstring_value.data(), size_needed);
+                }
+#else
                 std::wstring aux_wstring_value({value});
                 std::wstring_convert<std::codecvt_utf8<wchar_t>> converter;
                 std::string utf8_value = converter.to_bytes(aux_wstring_value);
+
+#endif  // defined(MINGW_COMPILER)
```
Comment (Javgilavi) [inline src/cpp/fastdds/xtypes/serializers/json/dynamic_data_json.cpp:762]: Same empty space here. I know can be seen irrelevant change, but it's needed to pass uncrustify CI
```suggestion
#endif  // defined(MINGW_COMPILER)
```

File: src/cpp/fastdds/xtypes/serializers/json/dynamic_data_json.cpp [hunk 7]
```diff
@@ -776,8 +789,18 @@ ReturnCode_t json_serialize_basic_member(
             if (RETCODE_OK == ret)
             {
                 // Insert UTF-8 converted value
+#ifdef MINGW_COMPILER
+                std::string utf8_value;
+                int size_needed = std::wcstombs(nullptr, value.data(), 0);
+                if (size_needed > 0)
```
Comment (Javgilavi) [inline src/cpp/fastdds/xtypes/serializers/json/dynamic_data_json.cpp:795]: Same space problem here
```suggestion
                if (size_needed > 0)
```

File: src/cpp/utils/SystemInfo.cpp [hunk 8]
```diff
@@ -155,9 +155,18 @@ fastdds::dds::ReturnCode_t SystemInfo::get_username(
 bool SystemInfo::file_exists(
         const std::string& filename)
 {
+#ifdef _WIN32
+    // modify for mingw
+    DWORD fileAttributes = GetFileAttributesA(filename.c_str());
+    if (fileAttributes == INVALID_FILE_ATTRIBUTES)
```
Comment (Javgilavi) [inline src/cpp/utils/SystemInfo.cpp:161]: And the last one to pass uncrustify CI
```suggestion
    if (fileAttributes == INVALID_FILE_ATTRIBUTES)
```

**Review by Javgilavi — COMMENTED** [review]
Sorry for being a bit picky with the review, but these changes are necessary to pass the CI.

**Comment by Javgilavi** [comment]
And for the DCO looks like it's still giving error.

Your new commit is fine: 
image

But in your original commit it still appears wrongly:
image
The "Signed-off-by: RookieCLY … " should appear in the second line (this automatically do with the commit -s) and also it says the commiter was "cuily" and not "RookieCLY", they need to be the same.

Follow the instruction of the DCO
image

If you have ant doubt about how to do it, just ask!!
And also thanks for the PR!!

**Review by Javgilavi — APPROVED** [review]
LGTM

**Comment by RookieCLY** [comment]
Hi, @Javgilavi . 
It seems that there is something wrong with MacOS CI, but I don't quite understand it. I just changed some code formats. What should I do next?

**Comment by Javgilavi** [comment]
Hi @RookieCLY,

Don't worry about it, it's not related to your changes.
It's not a problem.

**Comment by MiguelCompany** [comment]
@RookieCLY Failed test on MacOS is known to be flakey.

Thank you for your contribution and your patience!

**Comment by MiguelCompany** [comment]
@Mergifyio backport 3.1.x 3.0.x 2.14.x 2.10.x
