### PR TITLE
[13791] Several doxydoc improvements

### LINKED ISSUE #2609: [14256] reader is_sample_valid() return always false when DataSharing=On
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

when using `DataSharing` without using the `loan` API.
`is_sample_valid()` should return true on the reading samples

### Current behavior

`is_sample_valid()` return  false

### Steps to reproduce

Usage:
On reader creation:
`rqos.data_sharing().automatic();`

On reader usage:
```
        if( _reader->wait_for_unread_message( { 1, 0 } ) )
        {
            devices data;
            SampleInfo info;
            bool device_update_detected = false;
            // Process all the samples until no one is returned
            while( ReturnCode_t::RETCODE_OK == _reader->take_next_sample( &data, &info ) )
            {
                if( info.valid_data && _reader->**is_sample_valid**( &data, &info ) )
                {
. . .
```

setting `rqos.data_sharing().off` fix it.

@MiguelBarro , I think it had to do with `is_sample_valid()` implementation, treating `DataSharing` only as loan messages API.
See here: https://github.com/eProsima/Fast-DDS/blob/e8581dbe3e58905c108017eaa14ed225bcd8f76f/src/cpp/rtps/reader/RTPSReader.cpp#L397

As it seems the RTPS 2.3 extra header does not apply on DataSharing only, right?
 `is_sample_valid()` is only useful when using `loan` API?

### Fast DDS version/commit

Release 2.6.0

### Platform/Architecture

Windows 10 Visual Studio 2019

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

_No response_

### XML configuration file

_No response_

### Relevant log output

_No response_

### Network traffic capture

_No response_

### PR DESCRIPTION
**Pull request by MiguelCompany**
## Description
Adding missing doxydoc on ContentFilteredTopic methods.
Also removing some doc, as we don't need destructor or get_impl to be shown.

Closes #2609 

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] *N/A* Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally.  <-- Leaving this to eProsima/Fast-DDS-docs#361
- [x] *N/A* New feature has been added to the `versions.md` file (if applicable).
- [x] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

File: include/fastdds/dds/topic/ContentFilteredTopic.hpp [hunk 1]
```diff
@@ -55,26 +56,70 @@ class ContentFilteredTopic : public TopicDescription
 
 public:
 
-    /**
-     * @brief Destructor
-     */
     RTPS_DllAPI virtual ~ContentFilteredTopic();
```
Comment (JLBuenoLopez-eProsima) [inline include/fastdds/dds/topic/ContentFilteredTopic.hpp:59]: Following #2536, I think the `RTPS_DllAPI` should be removed. However, in order to merge this PR, we cannot do it right now. Maybe issuing another PR with this change and setting the milestone to `2.7.0` is the way to go.

File: include/fastdds/dds/topic/ContentFilteredTopic.hpp [hunk 2]
```diff
@@ -55,26 +56,70 @@ class ContentFilteredTopic : public TopicDescription
...
+     * This operation returns expression parameters associated with this ContentFilteredTopic.
+     * These will be the @c expression_parameters specified on the last successful call to @c set_expression or
+     * @c set_expression_parameters.
+     * If those methods have never been called, the expression parameters specified when the ContentFilteredTopic
+     * was created will be returned.
+     *
+     * @param [out] expression_parameters  The expression parameters currently associated with the
+     *                                     ContentFilteredTopic.
+     *
+     * @return RETCODE_OK
```
Comment (JLBuenoLopez-eProsima) [inline include/fastdds/dds/topic/ContentFilteredTopic.hpp:92]: Is this the only possible return code?

File: include/fastdds/dds/topic/ContentFilteredTopic.hpp [hunk 3]
```diff
@@ -85,10 +130,6 @@ class ContentFilteredTopic : public TopicDescription
      */
     virtual DomainParticipant* get_participant() const override;
```
Comment (JLBuenoLopez-eProsima) [inline include/fastdds/dds/topic/ContentFilteredTopic.hpp:131]:
```suggestion
    DomainParticipant* get_participant() const override;
```

`override` is enough to indicate that the method is `virtual`.

Also, this method is not being exported in Windows (`RTPS_DllAPI`) neither in the base clase (`TopicDescription`) nor here, so it is only part of the public API in non-Windows platforms. I think we should fix and export this method if it is intended to be used by the user and if not, remove the doxygen documentation so it does not appear in the API reference (and consider making the method protected).

File: include/fastdds/dds/topic/ContentFilteredTopic.hpp [hunk 4]
```diff
@@ -85,10 +130,6 @@ class ContentFilteredTopic : public TopicDescription
...
 
-    /**
-     * @brief Getter for the TopicDescriptionImpl
-     * @return pointer to TopicDescriptionImpl
-     */
     TopicDescriptionImpl* get_impl() const override;
```
Comment (JLBuenoLopez-eProsima) [inline include/fastdds/dds/topic/ContentFilteredTopic.hpp:133]: Maybe we should consider making the base method and the override implementations protected.

File: include/fastdds/dds/topic/TopicDescription.hpp [hunk 5]
```diff
@@ -65,21 +65,10 @@ class TopicDescription
...
     virtual TopicDescriptionImpl* get_impl() const = 0;
 
 protected:
 
-    /**
-     * @brief Constructor using topic name and data type name
-     *
-     * @param name Name for the topic
-     * @param type_name Data type name
-     */
```
Comment (JLBuenoLopez-eProsima) [inline include/fastdds/dds/topic/TopicDescription.hpp:82]: I think this can be kept because being a protected method Doxygen does not include it in the API reference. Same applies to the destructor.

File: include/fastdds/dds/topic/Topic.hpp [hunk 6]
```diff
@@ -75,9 +75,6 @@ class Topic : public DomainEntity, public TopicDescription
 
 public:
 
-    /**
-     * @brief Destructor
-     */
     virtual ~Topic();
```
Comment (JLBuenoLopez-eProsima) [inline include/fastdds/dds/topic/Topic.hpp:78]: Maybe we should consider making this destructor protected.

**Review by JLBuenoLopez-eProsima — CHANGES_REQUESTED** [review]
Some considerations. I think maybe a PR to be merged in `2.7.0` can be prepared with some of the suggestions.

File: include/fastdds/dds/topic/ContentFilteredTopic.hpp (hunk 2 above)
Comment (MiguelCompany) [reply include/fastdds/dds/topic/ContentFilteredTopic.hpp:92]: Yes

File: include/fastdds/dds/topic/ContentFilteredTopic.hpp (hunk 1 above)
Comment (MiguelCompany) [reply include/fastdds/dds/topic/ContentFilteredTopic.hpp:59]: I will do another PR removing the dll export.

File: include/fastdds/dds/topic/ContentFilteredTopic.hpp (hunk 4 above)
Comment (MiguelCompany) [reply include/fastdds/dds/topic/ContentFilteredTopic.hpp:133]: Having the implementation getter public makes no harm, as the user does not have the implementation class declaration.

Making this a protected method will break API, and require adding several friend classes.

File: include/fastdds/dds/topic/ContentFilteredTopic.hpp (hunk 3 above)
Comment (MiguelCompany) [reply include/fastdds/dds/topic/ContentFilteredTopic.hpp:131]: Removed the virtual on 55c498d, will do another PR adding the DLL export.

File: include/fastdds/dds/topic/Topic.hpp (hunk 6 above)
Comment (MiguelCompany) [reply include/fastdds/dds/topic/Topic.hpp:78]: That would break API. We may do it on a PR targetted for v3.0.

File: include/fastdds/dds/topic/TopicDescription.hpp (hunk 5 above)
Comment (MiguelCompany) [reply include/fastdds/dds/topic/TopicDescription.hpp:82]: I think the arguments have self explanatory names, so I don't think the doxydoc adds useful information

**Comment by MiguelCompany** [comment]
@JLBuenoLopez-eProsima I think I attended all your suggestions

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM. I would like to see the PR adding the Dll exports or at least a ticket opened in Redmine to ensure that we do not forget it.

File: include/fastdds/dds/topic/ContentFilteredTopic.hpp (hunk 1 above)
Comment (MiguelCompany) [reply include/fastdds/dds/topic/ContentFilteredTopic.hpp:59]: See #2611

File: include/fastdds/dds/topic/ContentFilteredTopic.hpp (hunk 3 above)
Comment (MiguelCompany) [reply include/fastdds/dds/topic/ContentFilteredTopic.hpp]: See #2611
