### PR TITLE
[13790] [13772] Link between DDS classes and DDSSQLFilter

### LINKED ISSUE #2450: Compile error when building fastdds 2.5.0 with foonathan_memory 0.7-1
Hi,

When building fastdds 2.5.0 with foonathan_memory 0.7-1 on GNU 5.5.0 I am getting a compilation error,

any reason why?

Thanks
```
2022-01-31T15:55:22.8306864Z In file included from /usr/include/x86_64-linux-gnu/c++/5/bits/c++allocator.h:33:0,
2022-01-31T15:55:22.8307214Z                  from /usr/include/c++/5/bits/allocator.h:46,
2022-01-31T15:55:22.8307453Z                  from /usr/include/c++/5/string:41,
2022-01-31T15:55:22.8307733Z                  from /usr/include/c++/5/bits/locale_classes.h:40,
2022-01-31T15:55:22.8308177Z                  from /usr/include/c++/5/bits/ios_base.h:41,
2022-01-31T15:55:22.8308415Z                  from /usr/include/c++/5/ios:42,
2022-01-31T15:55:22.8308657Z                  from /usr/include/c++/5/ostream:38,
2022-01-31T15:55:22.8308883Z                  from /usr/include/c++/5/iostream:39,
2022-01-31T15:55:22.8309409Z                  from /home/runner/work/librealsense/librealsense/build/third-party/fastdds/include/fastdds/rtps/common/Types.h:23,
2022-01-31T15:55:22.8309974Z                  from /home/runner/work/librealsense/librealsense/build/third-party/fastdds/include/fastdds/rtps/common/Guid.h:23,
2022-01-31T15:55:22.8310852Z                  from /home/runner/work/librealsense/librealsense/build/third-party/fastdds/src/cpp/fastdds/domain/DomainParticipantImpl.hpp:23,
2022-01-31T15:55:22.8311617Z                  from /home/runner/work/librealsense/librealsense/build/third-party/fastdds/src/cpp/fastdds/domain/DomainParticipantImpl.cpp:20:
2022-01-31T15:55:22.8313375Z /usr/include/c++/5/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> >; _Args = {std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, eprosima::fastdds::dds::ContentFilteredTopic*>}; _Tp = std::_Rb_tree_node<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> > >]’:
2022-01-31T15:55:22.8316282Z /usr/include/c++/5/bits/alloc_traits.h:530:4:   required from ‘static void std::allocator_traits<std::allocator<_CharT> >::construct(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, _Up*, _Args&& ...) [with _Up = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> >; _Args = {std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, eprosima::fastdds::dds::ContentFilteredTopic*>}; _Tp = std::_Rb_tree_node<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> > >; std::allocator_traits<std::allocator<_CharT> >::allocator_type = std::allocator<std::_Rb_tree_node<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> > > >]’
2022-01-31T15:55:22.8319274Z /usr/include/c++/5/bits/stl_tree.h:529:32:   required from ‘void std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_construct_node(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type, _Args&& ...) [with _Args = {std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, eprosima::fastdds::dds::ContentFilteredTopic*>}; _Key = std::__cxx11::basic_string<char>; _Val = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> >; _KeyOfValue = std::_Select1st<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> > >; _Compare = std::less<std::__cxx11::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> > >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type = std::_Rb_tree_node<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> > >*]’
2022-01-31T15:55:22.8322468Z /usr/include/c++/5/bits/stl_tree.h:546:21:   required from ‘std::_Rb_tree_node<_Val>* std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_create_node(_Args&& ...) [with _Args = {std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, eprosima::fastdds::dds::ContentFilteredTopic*>}; _Key = std::__cxx11::basic_string<char>; _Val = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> >; _KeyOfValue = std::_Select1st<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> > >; _Compare = std::less<std::__cxx11::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> > >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type = std::_Rb_tree_node<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> > >*]’
2022-01-31T15:55:22.8325121Z /usr/include/c++/5/bits/stl_tree.h:2152:33:   required from ‘std::pair<std::_Rb_tree_iterator<_Val>, bool> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_emplace_unique(_Args&& ...) [with _Args = {std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, eprosima::fastdds::dds::ContentFilteredTopic*>}; _Key = std::__cxx11::basic_string<char>; _Val = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> >; _KeyOfValue = std::_Select1st<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> > >; _Compare = std::less<std::__cxx11::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> > >]’
2022-01-31T15:55:22.8327949Z /usr/include/c++/5/bits/stl_map.h:560:64:   required from ‘std::pair<typename std::_Rb_tree<_Key, std::pair<const _Key, _Tp>, std::_Select1st<std::pair<const _Key, _Tp> >, _Compare, typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<std::pair<const _Key, _Tp> >::other>::iterator, bool> std::map<_Key, _Tp, _Compare, _Alloc>::emplace(_Args&& ...) [with _Args = {std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, eprosima::fastdds::dds::ContentFilteredTopic*>}; _Key = std::__cxx11::basic_string<char>; _Tp = std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic>; _Compare = std::less<std::__cxx11::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> > >; typename std::_Rb_tree<_Key, std::pair<const _Key, _Tp>, std::_Select1st<std::pair<const _Key, _Tp> >, _Compare, typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<std::pair<const _Key, _Tp> >::other>::iterator = std::_Rb_tree_iterator<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> > >]’
2022-01-31T15:55:22.8329731Z /home/runner/work/librealsense/librealsense/build/third-party/fastdds/src/cpp/fastdds/domain/DomainParticipantImpl.cpp:543:57:   required from here
2022-01-31T15:55:22.8330636Z /usr/include/c++/5/ext/new_allocator.h:120:4: error: no matching function for call to ‘std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<eprosima::fastdds::dds::ContentFilteredTopic> >::pair(std::pair<std::__cxx11::basic_string<char>, eprosima::fastdds::dds::ContentFilteredTopic*>)’
2022-01-31T15:55:22.8331239Z   { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }```

### PR DESCRIPTION
**Pull request by MiguelCompany**
This PR is built on top of #2464, and contains the following code:

* Blackbox test for content filtered topic
* Fix #2450
* Finish implementation of content filter on DDS layer
* Doxydoc for content filter interfaces

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@richiprosima Please test mac

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

File: include/fastdds/dds/topic/IContentFilterFactory.hpp [hunk 1]
```diff
@@ -45,6 +72,15 @@ struct IContentFilterFactory
...
 
+    /**
+     * Delete an IContentFilter instance.
+     *
+     * @param [in]  filter_class_name   Filter class name for which the factory is being called.
+     *                                  Allows using the same factory for different filter classes.
+     * @param [in]  filter_instance     A pointer to a filter instance previously returned by create_content_filter.
+     *                                  The factory takes ownership of the filter instance, and can decide to destroy
+     *                                  it or keep it for future use.
+     */
```
Comment (JLBuenoLopez-eProsima) [inline include/fastdds/dds/topic/IContentFilterFactory.hpp:83]: The `@return` information is missing

File: include/fastdds/dds/topic/ContentFilteredTopic.hpp [hunk 2]
```diff
@@ -49,9 +49,7 @@ class ContentFilteredTopic : public TopicDescription
 
     RTPS_DllAPI ContentFilteredTopic(
             const std::string& name,
-            Topic* related_topic,
-            const std::string& filter_expression,
-            const std::vector<std::string>& expression_parameters);
+            Topic* related_topic);
```
Comment (JLBuenoLopez-eProsima) [inline include/fastdds/dds/topic/ContentFilteredTopic.hpp:52]: The constructor is private but I am not sure if the virtual table would be modified by this change and thus affect ABI compatibility in `2.5.x`. Nobody is surely using this API because it was not previously implemented, but we should be aware of this issue.

**Review by JLBuenoLopez-eProsima — CHANGES_REQUESTED** [review]

File: include/fastdds/dds/topic/ContentFilteredTopic.hpp (hunk 2 above)
Comment (MiguelCompany) [reply include/fastdds/dds/topic/ContentFilteredTopic.hpp:52]: @EduPonz What do you think about this comment?

File: test/blackbox/common/DDSBlackboxTestsContentFilter.cpp [hunk 3]
```diff
@@ -16,6 +16,8 @@
 
 #include "PubSubWriter.hpp"
 
+#include "../types/HelloWorldTypeObject.h"
```
[the remark this answers is not in the document]
Comment (MiguelCompany) [reply test/blackbox/common/DDSBlackboxTestsContentFilter.cpp]: Commit e1b179cbcf6c3642f081de218bd49bd2b3b118c6

File: include/fastdds/dds/topic/IContentFilterFactory.hpp (hunk 1 above)
Comment (MiguelCompany) [reply include/fastdds/dds/topic/IContentFilterFactory.hpp:85]: Commit 1691cb0ad51e26655f7adf750b603bd5b9adbd34

File: include/fastdds/dds/topic/ContentFilteredTopic.hpp (hunk 2 above)
Comment (MiguelCompany) [reply include/fastdds/dds/topic/ContentFilteredTopic.hpp]: Kept ABI compatibility on commit 323fb2fcc9120da3bd0468ab931f1e1b4458d4ed

File: src/cpp/fastdds/topic/ContentFilteredTopicImpl.hpp [hunk 4]
```diff
@@ -55,6 +57,43 @@ class ContentFilteredTopicImpl final : public TopicDescriptionImpl, public epros
...
+            parameters = new_expression_parameters;
+            if (nullptr != new_expression)
+            {
+                expression = new_expression;
+            }
+
+            // TODO: inform data readers
+        }
+
+        return ret;
```
[the remark this answers is not in the document]
Comment (MiguelCompany) [reply src/cpp/fastdds/topic/ContentFilteredTopicImpl.hpp:94]: I promise to do this in the future, when implementing writer-side filtering.

The advantage of having it in the header is that I don't need to change the CMake files of all the unit tests that are using `DomainParticipantImpl`

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM! CI failures are unrelated
