### PR TITLE
Increasing GUID prefix uniqueness [10124]

### LINKED ISSUE #1633: Fast-DDS fails to transmit messages between containers on same Kubernetes pod [10123]
Setup: We run two processes in two different containers in the same pod in Kubernetes. A Kubernetes pod is a set of Docker containers with the same external IP. Each Kubernetes container has its own PID namespace. Process A in container A is a DDS publisher, process B in container B is a subscriber.

## Expected Behavior

Subscriber and publisher should be able to exchange messages.

## Current Behavior

Participant matching fails because both participants end up with the same GUID. This can be tracked down to both processes ending up with the same PID, because each container in Kubernetes has its own PID namespace. The GUID is created in FastRTPS from:

 - the MD5 host's external network interfaces (same in both processes, because same pod)
 - the process ID (same in both processes, because each is PID 2 in its container)
 - the participant ID (same in both processes, because they're assigned sequentially)

The problem is even more insidious when participant IDs don't happen to match: In this case, both FastDDS instances switch to intra-process delivery (because host MD5 and process ID match), and no messages are transmitted even though PDP succeeds.

The problem goes away when switching to host pids (shareProcessNamespace: true in the pod YAML).

## Why this is a problem

Kubernetes and other Docker-based orchestrators are getting more and more common. The PID has ceased to be a globally unique for kernels.

We fixed the problem internally by replacing GetPID() in RTPSDomain.cpp by a once-per-process call to rand(). I quickly wanted to give you heads-up and make this issue visible to others. ROS also ran into the same issue (https://github.com/ros2/rmw_fastrtps/issues/349) without understanding it fully.

### PR DESCRIPTION
**Pull request by MiguelCompany**
This should fix #1633 by using a random value on the 6-th and 7-th bytes of the GUID prefix.

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3293/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/504/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2940/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3325/)

File: src/cpp/rtps/common/GuidUtils.hpp [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+        //   announcement lease duration did not expire.
+        // In order to behave correctly in those situations, we will use the 16 least-significant bits of the PID,
+        // along with a random 16 bits value. This should not be a problem, as the PID is known to be 16 bits long on
+        // several systems. On those where it is longer, using the 16 least-significant ones along with a random value
+        // should still give enough uniqueness for our use cases.
+        int pid = SystemInfo::get().process_id();
+        prefix_.value[4] = static_cast<octet>(pid & 0xFF);
+        prefix_.value[5] = static_cast<octet>((pid >> 8) & 0xFF);
+
+        std::default_random_engine generator;
```
Comment (VladimirVassiliev) [inline src/cpp/rtps/common/GuidUtils.hpp:70]: This would generate the same number each time. I'd suggest using std::random_device instead.

Comment (MiguelCompany) [reply src/cpp/rtps/common/GuidUtils.hpp]: You're right! Done in fa8ae8309deefbf4338f41ab85872708be1bb11b

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3302/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/513/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2949/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3334/)

**Comment by richiware** [comment]
Can't set status; build failed.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3305/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/516/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2952/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3337/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3306/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/517/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2954/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3338/)

**Review by MiguelBarro — APPROVED** [review]
LGTM

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3312/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/523/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2960/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3344/)

**Comment by fujitatomoya** [comment]
confirmed this PR fixes https://github.com/eProsima/Fast-DDS/issues/1633 with kubernetes, talker and listener containers in the same pod can communicate.

**Comment by stevewolter** [comment]
Also confirmed that this patch solves the Kubernetes same-pod issue I'm seeing. Great work with the comments, this looks very well engineered.
