### PR TITLE
[19939] TCP deadlock on channel reuse

### LINKED ISSUE #4026: Frequently create/delete DataReader/Writer DomainParticipant in two application causes deadlock
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

No deadlock

### Current behavior

Thread of funtion ResourceEvent::unregister_timer is stucked.

### Steps to reproduce

Using some (about 3) TCP Client participants connect and create DataReader then delete the DataReader and disconnect to a TCP Server participant. Few minutes later, all participants are stucked.

### Fast DDS version/commit

2.11.2

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

TCPv4

### Additional context

1. It stucked at `ResourceEvent::unregister_timer` because it needed `cv_manipulation_` awake after `ResourceEvent::do_timer_actions()`.
unregister

2. In this case, `ResourceEvent::do_timer_actions()` triggered `RTPSParticipantImpl::sendSync`. And this function was waiting for `m_send_resources_mutex_` release.
sendsync

3. When new reader come this time, it called `RTPSParticipantImpl::createSenderResources` first and then held `m_send_resources_mutex_`.
createSender
Then it called `tcp_sender_resource->channel()->clear();`, wait the first thread join.
clear

I am not clear why it called `tcp_sender_resource->channel()->clear();`, I think it causes all thread stucked. 
Sorry for terrible description.

### XML configuration file

_No response_

### Relevant log output

_No response_

### Network traffic capture

_No response_

### PR DESCRIPTION
**Pull request by jepemi**
## Description

TCP channel reuse required joining the thread in charge of the previous channel. However, this call to `join()` involved taking some mutex that prevented the old thread from finishing its tasks, leading to a deadlock.
The disabling of the old channel has been relocated as well as the protection of some other channel resources.

@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

Fixes #4026 

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
-  *N/A* New feature has been added to the `versions.md` file (if applicable).
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

File: test/blackbox/common/TCPReqRepHelloWorldReplier.cpp [hunk 1]
```diff
@@ -41,6 +41,7 @@ using namespace eprosima::fastrtps::rtps;
 TCPReqRepHelloWorldReplier::TCPReqRepHelloWorldReplier()
     : request_listener_(*this)
     , reply_listener_(*this)
+    , reply_bussy_listener_(*this)
```
Comment (MiguelCompany) [inline test/blackbox/common/TCPReqRepHelloWorldReplier.cpp:44]: `bussy` -> `busy`. Applies to the whole PR

File: test/blackbox/common/TCPReqRepHelloWorldReplier.hpp [hunk 2]
```diff
@@ -118,14 +119,53 @@ class TCPReqRepHelloWorldReplier
     }
     reply_listener_;
 
+    class RequestBussyListener : public eprosima::fastrtps::PublisherListener
```
Comment (MiguelCompany) [inline test/blackbox/common/TCPReqRepHelloWorldReplier.hpp:122]: Instead of adding a new class, I would make the current `RequestListener` call a new `unmatched()` method in the replier, that will sleep when `use_busy_listener` is `true`

**Review by MiguelCompany — CHANGES_REQUESTED** [review]

**Comment by jepemi** [comment]
@richiprosima please test this

**Review by MiguelCompany — APPROVED** [review]

**Comment by chunyisong** [comment]
So,has this issue been solved ? Or another pr will resolve "TCP deadlock on channel reuse"? @EduPonz

**Comment by EduPonz** [comment]
Hi @chunyisong,

It has not been resolved yet, as we are currently undertaking some refactor on the TCP transport that will address this an other instabilities.
